### ISSUE TITLE
Kick off meeting for cloud-provider-aws

### ISSUE THREAD

**Issue by nckturner** [kubernetes/cloud-provider-aws#1]
On **Friday, April 13 9:00 AM PDT** we will discuss our approach to using this repository.  This may include repository structure, scope, migration strategy, any specifics about the components that people would like to discuss, and finally owners/contributors for areas of work.  (CSI, flex, CCM, ...)

Links: 
* [Zoom](https://zoom.us/j/787449961) 
* [SIG-AWS agenda & notes](https://docs.google.com/document/d/1-i0xQidlXnFEP9fXHWkBxqySkXwJnrGJP9OGyP2_P14/edit#)

**Comment by wlan0** [comment]
@nckturner There is a proposal by @hogepodge that details out the requirements for CCM repos - https://github.com/kubernetes/community/pull/1942

https://github.com/kubernetes/community/blob/master/keps/0002-controller-manager.md
