### ISSUE TITLE
Container images missing for newer releases

### ISSUE THREAD

**Issue by sdlarsen** [kubernetes/cloud-provider-aws#1010]
The latest image available on registry.k8s.io/provider-aws/cloud-controller-manager is v1.30.1

It's been a while since 1.30.2 was released, and now 1.30.3. Will they appear in time?

**Comment by dims** [comment]
cc @kmala @cartermckinnon

**Comment by xmudrii** [comment]
I created a PR to promote missing v1.30 and v1.29 images: https://github.com/kubernetes/k8s.io/pull/7143

I'll also look into missing v1.28 and v1.27 images and create a follow up PR if needed.

**Comment by kmala** [comment]
Thanks @xmudrii for the fix. We will make sure to update the new releases going forward.

/close

**Comment by xmudrii** [comment]
For completeness, v1.28 and v1.27 images were promoted as part of https://github.com/kubernetes/k8s.io/pull/7144
