### ISSUE TITLE
A Helm chart for deployment

### ISSUE THREAD

**Issue by TBBle** [kubernetes/cloud-provider-aws#119]
**What would you like to be added**:

A Helm chart for deployment. Based on a few other AWS projects, it probably makes sense to generate the example manifest from the Helm chart too, to support a single-source-of-truth.

**Why is this needed**:

Managing things by raw manifest doesn't give you version tracking, rollback, configurability, or any of the other nice features that Helm provides. Particularly for an in-development system, being able to rollback and inspect differences between working and non-working k8s resources is very helpful.

/kind feature

**Comment by jkroepke** [comment]
Are maintainers interest in a contribution?

I would like provide a chart based on the template + using GH pages to provide a chart and actions to automate this workflow.

**Comment by JESWINKNINAN** [comment]
@jkroepke are you working on this, can you please confirm?

**Comment by jkroepke** [comment]
No. Just ask if the maintainers are interest.
No response recived yet.

**Comment by ayberk** [comment]
@jkroepke Contributions are always welcome :) We would certainly appreciate if you can pick this up.

**Comment by JESWINKNINAN** [comment]
@ayberk Since @jkroepke is not yet started. I am assigned this issue to me

**Comment by jkroepke** [comment]
Alright, thanks for the note.
