### ISSUE TITLE
Friendly Load Balancer Names and Adopting Existing Load Balancers

### ISSUE THREAD

**Issue by voor** [kubernetes/cloud-provider-aws#124]
**What would you like to be added**:

Continuation of https://github.com/kubernetes/kubernetes/issues/29789 which is closed because of deprecation of in-tree providers:

> `a44e18e4c552b11e683bb02fff13e176` is not a very friendly ELB name. The AWS console does not allow for searching/sorting by tags for every resource. We use something like this:
> 
> ```
> [environment]-[app]
> staging-my-app
> ```
> 
> It would be nice if we could pick a template to use for naming. A combination of cluster name and pod name might work well.

**Why is this needed**:

Deletion for a Service Type of Load Balancer is a common occurrence, being able to adopt existing load balancers and give them easy to read names will greatly enhance the user experience of kubernetes on AWS.

Also adding in comment from @KIVagant as it's a very popular one:

> Why just not add something like `service.beta.kubernetes.io/aws-load-balancer-name` [to annotations](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L99) and allow users to manage this?

/kind feature

**Comment by glenjamin** [comment]
Is there anything blocking such an implementation, or does this just require someone to send in a PR for the functionality?

**Comment by voor** [comment]
> Is there anything blocking such an implementation, or does this just require someone to send in a PR for the functionality?

Think it's just the contribution, given we're positioning this such that we don't need to maintain backwards compatibility

**Comment by hryamzik** [comment]
![image](https://user-images.githubusercontent.com/1643962/109823393-f122a080-7c48-11eb-9ac6-c1329154bb4c.png)

**Comment by ayberk** [comment]
👀

/remove-lifecycle stale

**Comment by rifelpet** [comment]
FWIW, I added support in aws-load-balancer-controller to specify a custom NLB name: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1880

I've also confirmed that the controller can "adopt" existing NLBs by adding the appropriate tags to the load balancer and target groups: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/efe7e71d270e57a70d0c17587ee89237e055ee4d/pkg/deploy/tracking/provider.go#L9-L24

**Comment by nckturner** [comment]
I've started working on this.

**Comment by nckturner** [comment]
/hold
Need to figure out how to handle existing ELBs.

**Comment by roitalpaz** [comment]
is this working?
