### ISSUE TITLE
Tracking issue for v2 aws provider

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-aws#125]
**What would you like to be added**:
In https://github.com/kubernetes/cloud-provider-aws/pull/114 we added the initial boilerplate code to enable a v2 AWS cloud provider. This is a tracking issue for future PRs that add to the implementation. 

**Why is this needed**:
This project will continue to support the existing AWS provider in "out-of-tree" mode. However, there are many known issues and gaps in the current provider implementation that is not trivial to address. A new v2 implementation will try to address these limitations. The v2 implementation is a breaking change from v1 and is only supported for new clusters. Existing clusters cannot upgrade to v1. 

- [ ] Instances (@andrewsykim)  
 - [ ] Zones
- [ ] LoadBalancer (@HaibaraAi96) 
- [ ] Routes

/kind feature

**Comment by andrewsykim** [comment]
Some issues we should consider as we implement v2:
https://github.com/kubernetes/cloud-provider-aws/issues/124
https://github.com/kubernetes/cloud-provider-aws/issues/63
https://github.com/kubernetes/cloud-provider-aws/issues/55

**Comment by HaibaraAi96** [comment]
I'd love to work on the loadbalancer implementation 😃

**Comment by andrewsykim** [comment]
Sounds good @HaibaraAi96! I updated the tracking issue to break up the work here a bit and assigned the loadbalancer implementation to you. Feel free to use the legacy implementation as a reference https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/legacy-cloud-providers/aws

**Comment by rfranzke** [comment]
> The v2 implementation is a breaking change from v1 and is only supported for new clusters. Existing clusters cannot upgrade to v1.

What does this mean exactly, i.e., how will existing clusters be upgraded in the future (assuming the legacy AWS cloud provider code is being removed from k/k)?
