### ISSUE TITLE
More flexible NLB HealthCheck with HealthCheck payload

### ISSUE THREAD

**Issue by omzmarlon** [kubernetes/cloud-provider-aws#155]
**What would you like to be added**:
Make it configurable in a k8s service that the NLB HealthCheck can send a small HealthCheck payload to the target port or endpoint.

**Why is this needed**:
Right now the HealthCheck simply makes a TCP connection to a target port and if it can, the health check is successful. 
But some applications need more than that. For example, a typical Zookeeper liveness check may look like `command: ['/bin/bash', '-c', 'echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok']`
Without this ability, right now if I use an NLB Load Balancer service to expose a cluster of Zookeeper pods, the server logs errors like this: 
```
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /x.x.x.x:xxxx, session = 0x0
```
because it expects a ZK server command in the connection established. 

/kind feature

**Comment by justinsb** [comment]
We discussed in provider-aws, one possible workaround might be to have an "adapter" sidecar container that speaks HTTP; NLB health-checks that sidecar container; the sidecar container would respond based on doing a Zookeeper health-check.
