### ISSUE TITLE
annotation to create service-endpoint (PrivateLink)

### ISSUE THREAD

**Issue by nimrodishi** [kubernetes/cloud-provider-aws#177]
**What would you like to be added**:
Currently there are annotations to create an NLB.
I want the option to either:
1. pass an existing NLB arn/id and use this
2. Or; having an annotation that creates an Endpoint Service (for PrivateLink purposes)

**Why is this needed**:
As I mentioned in (2), there's currently no way to do this.
I have to let k8s service generate the nlb for me, and then manually (or using tf) add n Endpoint. This is bad for automation as we use TF and I would like to run some basic tf code, and then install (using helm) my app, and not have to to terraform - helm - terraform fixes again.
This is also an issues cause If I do helm changes, tf won't be aware.

Original issue: https://stackoverflow.com/questions/66121683/creating-a-service-endpoint-for-a-service-in-eks

Thanks!

/kind feature

**Comment by rifelpet** [comment]
This will likely be implemented in the aws-load-balaner-controller. I recommend subscribing to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1859
