### ISSUE TITLE
[Enhancement] Support internal NLB using private IP per subnet

### ISSUE THREAD

**Issue by hypervtechnics** [kubernetes/cloud-provider-aws#187]
**What would you like to be added**:

Already implemented in the CLI using the `--subnet-mappings [...]` argument: https://docs.aws.amazon.com/cli/latest/reference/elbv2/create-load-balancer.html
An additional annotation like `service.beta.kubernetes.io/aws-load-balancer-subnet-ips: 123.456.789.000,987.654.321.000` or an extension to the existing annotation `service.beta.kubernetes.io/aws-load-balancer-subnets` would be nice to cover that one. Or even a similar behaviour to the CLI using e.g. `service.beta.kubernetes.io/aws-load-balancer-subnet-mappings: SubnetId=subnet-123456,PrivateIPv4Address=123.456.789.000`.

(Yeah I know those are not valid IPs - you get the point)

**Why is this needed**:

In certain scenarios the customer wants to create a DNS entry in their system pointing to the **fixed** IPs of the load balancer. As we are using Terraform to build the cluster the Ingress Controller gets redeployed quite often meaning that the IPs change with each deployment. This is unnecessary work to adjust the DNS and Firewall settings each time the cluster gets redeployed. You seem to have already understood why it is needed as the feature is already implemented in AWS itself... Sadly not in the controller.

Also mentioned in #108 which did not receive an answer...

/kind feature

**Comment by nckturner** [comment]
This will be supported in the 2.2.0 of the aws-load-balancer-controller, is that something you can use?

**Comment by mimmus** [comment]
> This will be supported in the 2.2.0 of the aws-load-balancer-controller, is that something you can use?
How could I use it?
Is there any chance to see it in classic Nginx controller?
