### ISSUE TITLE
Helm repo is not working

### ISSUE THREAD

**Issue by yuvraj9** [kubernetes/cloud-provider-aws#188]
**What happened**:
Helm repo is not working. Getting below error

```Error: looks like "https://github.com/kubernetes/cloud-provider-aws" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/kubernetes/cloud-provider-aws/index.yaml : 404 Not Found```

**What you expected to happen**:
Running helm add command should have added the repository but its failing

**How to reproduce it (as minimally and precisely as possible)**:
Run this command - ```helm repo add aws-cloud-controller-manager https://github.com/kubernetes/cloud-provider-aws```

/kind bug

**Comment by ayberk** [comment]
Unfortunately we're currently not serving the charts anywhere because we're using github pages for our documentation. This is on my list and I'll update the ticket when it's resolved.

I'm afraid the only way to install it via helm right now is cloning the repo and installing directly from the local folder.

**Comment by JESWINKNINAN** [comment]
@ayberk Can you please assign this issue to me

**Comment by ayberk** [comment]
@JESWINKNINAN Where are you planning to host the charts? I was planning to move docs to another hosting solution and use gh-pages for our helm charts.

**Comment by JESWINKNINAN** [comment]
@ayberk Hope the new PR will fix the issue?

**Comment by ayberk** [comment]
@JESWINKNINAN yep. It worked on my fork, but let me know if it doesn't work for you.

**Comment by nckturner** [comment]
Closing, https://github.com/kubernetes/cloud-provider-aws/pull/191 should resolve this.
