### ISSUE TITLE
Add NLB support for BYOIP PublicIpv4Pool parameter

### ISSUE THREAD

**Issue by zenvdeluca** [kubernetes/cloud-provider-aws#196]
AWS customers that make usage of [AWS BYOIP feature](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-byoip.html), when provisioning public network load balancers (NLBs), it requires a two-step process where:

1: provision Elastic IPs referencing an existing BYOIP ipv4 pool
```public-ipv4-pool (string)

The ID of an address pool that you own. Use this parameter to let Amazon EC2 select an address from the address pool. To specify a specific address from the address pool, use the Address parameter instead.
``` 

2: Provision an NLB referencing the EIPs created on Step 1

We need the functionality of passing our ipv4pools as an annotation, such as:

```
service.beta.kubernetes.io/aws-load-balancer-public-ipv4-pool: ipv4pool-ec2-0f123678912345678
service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```

that would result in provisioning the Network Load Balancer with public IPv4 from our BYOIP pools

**Comment by JoelSpeed** [comment]
@kishorj You've marked this as a duplicate, but LB controller and the CCM are separate products with separate user bases and in some cases, separate use cases. Is the feature supported on both the CCM and the LB controller, and if not, can we backport it from the LB controller to the CCM?

**Comment by oliviassss** [comment]
@JoelSpeed, I checked with the NLB team internally, unfortunately BYOIP is not yet supported by NLB, they are planning for H2 2024.
