### ISSUE TITLE
Test framework for e2e tests

### ISSUE THREAD

**Issue by nckturner** [kubernetes/cloud-provider-aws#198]
Let's create a framework for e2e testing.  I suggest we borrow the structure of the ebs-csi-driver e2e tests (see [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/tests/e2e)).

**Comment by andrewsykim** [comment]
This project is really early stages but might be worth trying out https://github.com/kubernetes-sigs/e2e-framework
