### ISSUE TITLE
Investigate importing this repository from k/k

### ISSUE THREAD

**Issue by nckturner** [kubernetes/cloud-provider-aws#202]
Determine if we should import the v1 provider in this repository into the staging legacy-cloud-provider location, or just continue cherry-picking bug fixes until the code is removed from k/k.  

/cc @andrewsykim @cheftako

**Comment by cheftako** [comment]
This repo imports parts of K/K staging so I would say its not safe to import it into any of the K/K public repos. However I do not see it importing anything from K/K private. As long as that remains true, I think it should be safe to import it in K/K private. So you could use it for things like Kubelet, KAS and KCM.

**Comment by nckturner** [comment]
We're not going to do this.
/close
