### ISSUE TITLE
User story for AWS load balancer controller

### ISSUE THREAD

**Issue by nckturner** [kubernetes/cloud-provider-aws#203]
Our story around the cloud-controller-manager and the aws-load-balancer-controller is not clear, and is made worse by the fact that NLB functionality is split across the two [[1]](https://github.com/kubernetes/cloud-provider-aws/issues/196).

Some thoughts: 
1. We should move all NLB functionality to the aws-load-balancer-controller.
2. We should unify the installation method (for most common use cases) so that users do not have to do "extra work" to get the same functionality.  I think this is accomplished with a unified helm chart, and kops config file support.   

An alternative to (1) is we import the aws-load-balancer controller as a library here, but I'm not sure its necessary if the only benefit is slightly easier installation. 

/cc @M00nF1sh @kishorj

**Comment by nckturner** [comment]
Add messaging for users that encourages them to migrate to the aws-load-balancer-controller, eventually should we introduce a feature gate that is on by default, which disables the in-tree NLB functionality?

**Comment by ostrain** [comment]
As a user, I'm confused by this. I don't understand the relationship between cloud-provider-aws and aws-load-balancer-controller. Does the latter depend on the former, while providing an alternative implementation of NLB orchestration? How should they be used together?

**Comment by nckturner** [comment]
/reopen

Essentially cloud-provider-aws is a copy of the in-tree cloud provider, which has the original code for provisioning classic load balancers and NLBs for services of type `LoadBalancer`. Cloud-provider-aws supports instance target type for NLBs.  

The AWS load balancer controller is a more recent controller, which can provision ALBs for ingress resources, and NLBs for services of type `LoadBalancer`.  Originally it only supported the IP target type for NLBs, but since 2.2.0 it has also supported instance target type.  

The goal of this task is to define what I think the future should be, which is probably deprecating NLB support in the in-tree provider, since it has essentially been replaced by the AWS load balancer controller. Also, we should determine whether we are happy with asking users to separately install the AWS load balancer controller, or if we should support a bundled install to make things easier.

**Comment by julienperignon** [comment]
Jumping on this thread because I was in the same scenario of not understand who's responsible of what. 
Is there a way to disable the in-tree controller and let the aws-controller create NLB for target type = instance ? 

Cheers

**Comment by julienperignon** [comment]
> The AWS load balancer controller is a more recent controller, which can provision ALBs for ingress resources, and NLBs for services of type `LoadBalancer`. Originally it only supported the IP target type for NLBs, but since 2.2.0 it has also supported instance target type.

Jumping on this thread because I was in the same scenario of not understand who's responsible of what.
Is there a way to disable the in-tree controller and let the aws-controller create NLB for target type = instance ?

Cheers

**Comment by sftim** [comment]
@julienperignon 

> Is there a way to disable the in-tree controller and let the aws-controller create NLB for target type = instance ?

I recommend also filing this via https://github.com/aws/containers-roadmap/issues/new/choose

**Comment by malt3** [comment]
Please reopen this. And please document somewhere in this repo that the other controller exists (and is probably the one you want).
This is causing pain and confusion.
