### ISSUE TITLE
AWS CCM doesn't attach instances automatically to the Classic LB

### ISSUE THREAD

**Issue by nurhun** [kubernetes/cloud-provider-aws#208]
**What happened**:
I'm using AWS cloud controller with Ingress nginx on k3s cluster. It initializes classic lb for LoadBalancer services successfully but it doesn't attach instances to it, generating url with empty response.

**What you expected to happen**:
Attaching instances owned by the cluster to the lb automatically.

**How to reproduce it (as minimally and precisely as possible)**:
Run LoadBalancer service on k3s cluster with AWS CCM & nginx ingress.

**Anything else we need to know?**:
Tags are set as advised on VPC, EC2, Subnets, Routing Tables, Internet Gateway, Security groups
kubernetes.io/cluster/default = owned

Subnets tagged with below as well,
kubernetes.io/role/elb = 1

EC2 additional tag
k8s-control-plane

IAM role configured and attached as instructed.

Ingress resource annotated as below,
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/subnets: public_subnet_1, public_subnet_2, public_subnet_3

**Environment**:
- Kubernetes version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-16T19:04:44Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-16T19:04:44Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
AWS

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):
Linux ip-10-0-2-28.eu-north-1.compute.internal 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
k3s

/kind bug

**Comment by Juneezee** [comment]
I am facing this issue as well. In my case, I created a Kubernetes with 1 control plane and 1 worker node using kubeadm. 

`kubectl expose deployment example-deployment --type=LoadBalancer --name=example-service` does create a classic load balancer, but I have to manually attach the load balancer to my worker node for it to work.

**Comment by nckturner** [comment]
> It initializes classic lb for LoadBalancer

So is the issue with CCM and a service of type load balancer?  You've also provided information about the ingress resource, but I'm not sure how that fits into the picture.
