### ISSUE TITLE
cloud-controller-manager image should support arm64

### ISSUE THREAD

**Issue by Juneezee** [kubernetes/cloud-provider-aws#219]
**What would you like to be added**:
The [cloud-controller-manager](gcr.io/k8s-staging-provider-aws/cloud-controller-manager) should support `arm64` architecture.

**Why is this needed**:
The latest AWS EC2 instances (e.g. t4g, m6g, c6g, etc.) are ARM64.

/kind feature

**Comment by olemarkus** [comment]
/remove-lifecycle stale

As kOps is migrating towards using external CCMs, this has become quite important. AWS external CCM is enabled by default as of Kubernetes 1.24 (i.e our master branches) and the moment, all our arm tests are failing.
