### ISSUE TITLE
Pass tags in the CreateSecurityGroup and CreateLoadBalancer API call

### ISSUE THREAD

**Issue by YYashwanth** [kubernetes/cloud-provider-aws#220]
Hello,

I have a scenario where we have an AWS SCP restricting the creation of security groups and ELBs that are not tagged. When we create a service of type LoadBalancer, EKS creates the LoadBalancer, creates the security group and then does an CreateTags API call to add tags to the security group and a AddTags API call to add tags on the ELB.

As a result of the various API calls, the resource creation fails.

Right now the API calls are like this:
- CreateSecurityGroup
- CreateLoadBalancer
- CreateTags (for sec group)
- AddTags (for elb)

**What would you like to be added**:

Passing of tags mentioned in the **service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags:** in the same API call as CreateLoadBalancer and CreateSecurityGroup.

**Why is this needed**:

As mentioned above, creation of Services in EKS fails when we have SCPs restricting the creation of untagged resources.

/kind feature

**Comment by nckturner** [comment]
This seems like a reasonable feature -- also should be a relatively easy change so if anyone would like to contribute this we would be happy to accept it!

**Comment by giorgosdi** [comment]
I can give this a go. Could i have some guidance on how to actually test that it works ? i.e can i use minikube or kind ?

**Comment by olemarkus** [comment]
Can you check if #293 solves your issue?

**Comment by YYashwanth** [comment]
@olemarkus thanks for the MR. I will check this out tomorrow and get back to you asap.

**Comment by olemarkus** [comment]
I guess the linked PR worked :)
