### ISSUE TITLE
Helm chart v 0.0.3 - ImagePullBackOff - Failed to pull image - not found

### ISSUE THREAD

**Issue by nurhun** [kubernetes/cloud-provider-aws#228]
**What happened**:
getting error "ImagePullBackOff" when trying to install latest helm chart.

Logs:
- Pulling image "gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0"
- Failed to pull image "gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0": rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0": failed to resolve reference "gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0": gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0: not found
- Error: ErrImagePull
- Error: ImagePullBackOff
- Back-off pulling image "gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0"

**What you expected to happen**:
Install replica on each master nodes.

**How to reproduce it (as minimally and precisely as possible)**:
k3s cluster 
Client Version: v1.21.1+k3s1
Server Version: v1.21.1+k3s1

Using below steps,
helm repo --kubeconfig /etc/rancher/k3s/k3s.yaml add aws-cloud-controller-manager https://kubernetes.github.io/cloud-provider-aws
helm repo update
helm install aws-cloud-controller-manager aws-cloud-controller-manager/aws-cloud-controller-manager

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: v1.21.1+k3s1
Server Version: v1.21.1+k3s1

- Cloud provider or hardware configuration: AWS

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):
Linux ip-10-0-4-170.ec2.internal 5.4.0-1048-aws #50-Ubuntu SMP Mon May 3 21:44:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: k3s
- Others:

/kind bug

**Comment by nurhun** [comment]
any updates here guys

**Comment by mstefany** [comment]
Seems that only `v20210510-v1.21.0-alpha.0`, `v20210520-v1.21.0-alpha.0-2-g54f2b5c` and `v20210623-v1.21.0-alpha.0-4-g7d6f102` tags were generated for the images, no simple `v1.21.0-alpha.0` as with previous release.

**Comment by pschulten** [comment]
same with the cloud-controller image:
```console
$ docker pull gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0
Error response from daemon: manifest for gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0 not found: manifest unknown: Failed to fetch "v1.21.0-alpha.0" from request "/v2/k8s-staging-provider-aws/cloud-controller-manager/manifests/v1.21.0-alpha.0".
```

v1.20.0 works
```console
$ docker pull gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.20.0-alpha.0
v1.20.0-alpha.0: Pulling from k8s-staging-provider-aws/cloud-controller-manager
9ff2acc3204b: Pull complete
e94562e100ba: Pull complete
Digest: sha256:533d2d64c213719da59c5791835ba05e55ddaaeb2b220ecf7cc3d88823580fc7
Status: Downloaded newer image for gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.20.0-alpha.0
gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.20.0-alpha.0
```
