### ISSUE TITLE
Any way to use that after --cloud-provider=aws deprecated?

### ISSUE THREAD

**Issue by yunusemrecatalcam** [kubernetes/cloud-provider-aws#231]
**What happened**:
I'm creating a self-managed k8s cluster on an ec2, I wanna use ebs on it. However, I got some error with the cloud provider while using dynamic provisioning/mounting and existing snapshot on ebs with the kubernetes.io/aws-ebs provisioner. 

Just to check, I installed ebs-csi, ebs.csi.aws.com provisioner, volumes works fine.

I'm seeing passing --cloud-provider=aws flag to kubeadm init everywhere but its not working anymore.
I couldn't find a proper documentation about this repo, saw this https://cloud-provider-aws.sigs.k8s.io/getting_started/
but the manifest is not even working, image can not be found.

I also saw this issue 
https://github.com/kubernetes/cloud-provider-aws/issues/86
but it looks like they're chatted, made some workaround and pass lol

So I'm curious about how this repo is being used, I guess that kops may using that, but not having a documentation on how to install? Is that mean we have to use kops if we wanna set up an aws integrated cluster?

I'm really curious and if you need someone to contribute, here I am, I think we need to figure this out.

/kind bug

**Comment by johnsca** [comment]
It looks like they forgot a tag on [the image](https://console.cloud.google.com/gcr/images/k8s-staging-provider-aws/GLOBAL/cloud-controller-manager@sha256:30fc096f4a4609cb5f6c66c70856d59403ab8b396c1e90c78801db3b78ddcc8d/details?tab=info) and you could change it to use `v20210510-v1.21.0-alpha.0` instead. That definitely should be fixed, though.

**Comment by johnsca** [comment]
#245 would fix the manifest, at least. The image tag should probably also be added.
