### ISSUE TITLE
Helm Template Doesnt Use extraArgs to daemonset

### ISSUE THREAD

**Issue by jtcarnes** [kubernetes/cloud-provider-aws#235]
**What happened**:

Currently, the helm template for the daemonset does not utilize the `extraArgs` key at all. It is intended
to allow users to specify additional arguments to the daemonset.

**What you expected to happen**:

Values in the `extraArgs` key should be provided to the daemonset as arguments.

**How to reproduce it (as minimally and precisely as possible)**:

Look at the helm template for daemonset.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by ozlotusflare** [comment]
Hey @nckturner  
could you, please, take a look ?
