### ISSUE TITLE
Dualstack support for NLB

### ISSUE THREAD

**Issue by MMeent** [kubernetes/cloud-provider-aws#243]
**What would you like to be added**:

Support for dualstack NLB LoadBalancer services

**Why is this needed**:

Right now, NLBs are not deployed with dualstack, even if the VPC supports dualstack, and it's important to support IPv6, even if it's only for ingress traffic.

/kind feature

**Comment by rastislavs** [comment]
/reopen

Are there any plans for supporting this?
