### ISSUE TITLE
Charts / Manifests refer to tag v1.21.0-alpha.0, which doesn't exist

### ISSUE THREAD

**Issue by joedborg** [kubernetes/cloud-provider-aws#244]
https://github.com/kubernetes/cloud-provider-aws/blob/master/manifests/base/aws-cloud-controller-manager-daemonset.yaml#L31 and https://github.com/kubernetes/cloud-provider-aws/blob/master/charts/aws-cloud-controller-manager/values.yaml#L8 refer to `v1.21.0-alpha.0`, which doesn't seem to exist: https://console.cloud.google.com/gcr/images/k8s-staging-provider-aws/GLOBAL/cloud-controller-manager?gcrImageListsize=30&gcrImageListsort=-created%252C-uploaded

This ends up in an `ErrImagePull`. 

I guess `v20210510-v1.21.0-alpha.0` is the correct tag.

**Comment by elgamal2020** [comment]
Same issue , I corrected the tag to the daemonset to v20210510-v1.21.0-alpha.0
