### ISSUE TITLE
Classic ELB reconciliation requires unfiltered DescribeInstances call

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/cloud-provider-aws#269]
**What happened**:

The Classic ELB reconciliation code uses ec2.DescribeInstances to find all relevant instance IDs that should be added to the Classic ELB:

`findInstancesForELB` calls `describeAllInstancesCached` which calls `describeAllInstancesUncached` which calls `describeInstances`

https://github.com/kubernetes/cloud-provider-aws/blob/954bbd1f9b5ef824d1783b3e0ee8672061a3b052/pkg/providers/v1/aws_loadbalancer.go#L1600-L1617

https://github.com/kubernetes/cloud-provider-aws/blob/954bbd1f9b5ef824d1783b3e0ee8672061a3b052/pkg/providers/v1/instances.go#L196-L208

https://github.com/kubernetes/cloud-provider-aws/blob/954bbd1f9b5ef824d1783b3e0ee8672061a3b052/pkg/providers/v1/instances.go#L152-L162

https://github.com/kubernetes/cloud-provider-aws/blob/954bbd1f9b5ef824d1783b3e0ee8672061a3b052/pkg/providers/v1/aws.go#L5125-L5141

Notice that describeAllInstancesUncached does not provide any filters to the underlying `ec2.DescribeInstances`.

In accounts with many (10s of thousands) of instances in one region, this call is very slow and even fails with HTTP 500 responses. This causes reconciliation of the Classic ELB's instances to fail. Over time this can lead to fewer and fewer instances behind the ELB due to node attrition which could lead to service disruption.

**What you expected to happen**:

The `ec2.DescribeInstances` call should have sufficient filters to reduce its scope as much as possible.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Adding filters to DescribeInstances could reduce the scope sufficiently that the AWS API will consistently succeed and in reasonable time.

Notice in the last code block above that the list of instances in the response is then filtered to only those that include the cluster tag:

https://github.com/kubernetes/cloud-provider-aws/blob/954bbd1f9b5ef824d1783b3e0ee8672061a3b052/pkg/providers/v1/tags.go#L133-L151

This checks if the instance has either `kubernetes.io/cluster/clustername=` or `KubernetesCluster=clustername` tags.

I'm wondering if we could include these in the request's filters instead. The EC2 API responds with the intersection of multiple filters, so it may be difficult to filter for the union of those tags. We may also be able to explore the [ResourceGroupTagging API](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi#Client.GetResources) to get the list of instance IDs. If the controller doesn't have the cluster name (ClusterID) set, it could fallback to the existing behavior.

Additionally, since Classic ELBs [can only target instances in the same VPC](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-deregister-register-instances.html#elb-register-instances-prereq), if the VPC ID is known around this area of code we could include it in the filter too.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: AWS

/kind bug

**Comment by randomvariable** [comment]
This is fair, but we will require fall back code if ResourceGroupTagging API is used since it's not available as a VPC endpoint, which affects airgapped scenarios (particularly GovCloud and Secret regions).

**Comment by rifelpet** [comment]
After some investigation, I believe ResourceGroupTagging has the same limitation on not being able to filter on the union of two tag keys, so we might as well stick with DescribeInstances to avoid the VPC Endpoint limitation and IAM policy changes required for RGT.

We could call DescribeInstances twice, one for `kubernetes.io/cluster/` and one for `KubernetesCluster` but that seems a bit redundant though it will be cached.

Alternatively, is there a deprecation plan for the `KubernetesCluster` tag? We could only filter on `kubernetes.io/cluster/`.

**Comment by randomvariable** [comment]
>  is there a deprecation plan for the KubernetesCluster tag

i had completely forgotten about this. Let's create a new issue for this. FIltering only on the latter is reasonable.
