### ISSUE TITLE
AWS node/instance security group - misuse of cluster tag

### ISSUE THREAD

**Issue by Benjamin-Dobell** [kubernetes/cloud-provider-aws#27]
Cross post of k8s issue. **Aside:** Is there an official policy on where cloud provider issues should be opened?

---

The AWS cloud provider cluster tag, which defines ownership semantics, is presently being utilised improperly for unrelated purposes. In particular, _attempting_ to identify which instance security groups should be updated to allow inbound load balancer traffic.

This means we (or our controllers) are unable to attach additional security groups to our instances (without "leaking" security group resources).

Please refer to the upstream issue for further details [kubernetes/kubernetes#73906](https://github.com/kubernetes/kubernetes/issues/73906)

**Comment by Benjamin-Dobell** [comment]
Upstream issue https://github.com/kubernetes/kubernetes/issues/73906

**Comment by Pratima** [comment]
Completely agree. Would like to bump this post. We can't use istio nlb ingress with our worker pools that have multiple security groups.
We use [Terraform AWS EKS module](https://github.com/terraform-aws-modules/terraform-aws-eks) to setup our cluster.

**Comment by Benjamin-Dobell** [comment]
Looks like the [cluster-api-provider-aws has new tags](https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.3.2): 

> Labels for Cluster API managed infrastructure and cloud-provider managed infrastructure overlapped. The breaking change introduces a new label for Cluster API to use as well as a tool to convert labels on existing clusters to the new format.

I'm still using Kops, but keen to migrate.

However, it looks like the cloud-provider still [documents the `owned` cluster tag as being tied to the lifecycle of the cluster](https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/cloudprovider/providers/aws/tags.go#L45):

```go
	// ResourceLifecycleOwned is the value we use when tagging resources to indicate
	// that the resource is considered owned and managed by the cluster,
	// and in particular that the lifecycle is tied to the lifecycle of the cluster.
        ResourceLifecycleOwned = "owned"
```

Perhaps the intention is that this tag now signifies ownership by the _cloud-provider_ (rather than the cluster)?

Would appreciate it if a maintainer could chime in clarifying the situation.

**Comment by manvendra-singh0x7cd** [comment]
@Benjamin-Dobell  Any updates on this ?

**Comment by xjtupdy** [comment]
@Pratima Could you tell how did you solve it when using [Terraform AWS EKS module](https://github.com/terraform-aws-modules/terraform-aws-eks)
