### ISSUE TITLE
Deprecate and remove support of the KubernetesCluster tag 

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/cloud-provider-aws#271]
The `KubernetesCluster` tag is considered "legacy" and is replaced by the more-flexible `kubernetes.io/cluster/<clustername>` tag:

https://github.com/kubernetes/cloud-provider-aws/blob/58bc609b9f79e1283b8896011f1590691604b2aa/pkg/providers/v1/tags.go#L30-L39

We should adopt a timeline for a formal deprecation and removal of any use of `KubernetesCluster`.

/kind deprecation

**Comment by nckturner** [comment]
Agreed.  It has already been deprecated, so I think we can drop it in the next minor version release.

**Comment by nckturner** [comment]
The safer alternative, if we think this tag is still being used, is to amplify the existing deprecation messages for a release or two, and then drop it.

**Comment by nckturner** [comment]
Alas, I thought there was a deprecation log message, but I can't find one... only the comment you linked.  Looks like we will need to add one and determine a schedule, as you mentioned.
