### ISSUE TITLE
Cut release for 1.23

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/cloud-provider-aws#294]
**What would you like to be added**:

Please cut a release for use with Kubernetes 1.23.

**Why is this needed**:

Kubernetes 1.23.0 has been released. Users should have a fixed tag for pulling a corresponding AWS CCM.

/kind feature

**Comment by ialidzhikov** [comment]
@nckturner , why all releases are marked as alpha? Do we have ETA for a stable release of cloud-provider-aws?
For reference, cloud-provider-azure has stable/GA releases since a long time - ref https://github.com/kubernetes-sigs/cloud-provider-azure#current-status.
