### ISSUE TITLE
Support Availability Zone ID topology labels

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/cloud-provider-aws#300]
**What would you like to be added**:
Currently AWS CCM populates the `topology.kubernetes.io/region` and `topology.kubernetes.io/zone` node labels with the node's region and AZ name respectively:

```yaml
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1a
```

It would be useful to include a topology label for AZ IDs. `topology.kubernetes.io/zone-id` or something along those lines. Only the original two labels [are standard in the k/k API](https://github.com/kubernetes/kubernetes/blob/d90342e500a43e5112da04ecefa0c9ae1b1fb6c2/staging/src/k8s.io/api/core/v1/well_known_labels.go#L22-L23) so we'll need to decide on a new label to use.

```yaml
    topology.k8s.aws/zone-id: use1-az1
```
**Why is this needed**:

For inter-cluster communication that spans AWS accounts, ensuring zonal isolation becomes challenging when the accounts do not have the same AZ mappings. By including AZ ID information in topologies we can more easily ensure that workloads are scheduled to consistent AZ IDs and communicate with other workloads in the same AZ ID regardless of their AWS account or the account's AZ mapping.

/kind feature

**Comment by olemarkus** [comment]
Yes please! We have the exact same need.

**Comment by olemarkus** [comment]
Actually, I wonder if not the zone label could change to using zone IDs. I think the transition should be fairly painless as the new CCM leader would just patch all existing nodes.

**Comment by rifelpet** [comment]
If we reuse the `zone` topology label then there may be strange behavior of pod topology spread constraints during the upgrade process when nodes have a mismatch of zone IDs and zone names.

Its common for zonal deployments to use nodeAffinity on specific `zone` label values, so updating the `label` value in place would break their scheduling as well.

**Comment by olemarkus** [comment]
Spread constraints is only evaluated during scheduling, so this shouldn't be affected.

But nodeAffinity on a given zone label can cause problems, I suppose.

**Comment by rifelpet** [comment]
An alternative AWS-specific label could be `topology.k8s.aws/zone-id`

**Comment by rifelpet** [comment]
sig-cloud-provider agreed to use an AWS-specific label and/or the ability to configure CCM to use the zone ID in the `topology.kubernetes.io/zone` label

**Comment by andrewsykim** [comment]
> configure CCM to use the zone ID in the topology.kubernetes.io/zone label

My only caution to using zone-id in `topology.kubernetes.io/zone` is that it could negatively impact portability of deployments across different AWS accounts.

**Comment by olemarkus** [comment]
E.g EBS CSI drivers use topology keys and changing the convention on a live cluster may cause problems with PVs. So I think the safer route is to add new labels for now. I'd really like zone to use zone-ids, but it seems like too many things may break over it.

**Comment by sftim** [comment]
Reposting from https://github.com/aws/containers-roadmap/issues/1638#issuecomment-1049045011

`topology.kubernetes.io/zone-id` is **not** [registered](https://kubernetes.io/docs/reference/labels-annotations-taints/) as a Kubernetes label key. To report an AWS-specific detail, I recommend minting one or two new label keys. For example:
- `kubernetes.amazonaws.example/availability-zone: us-east-1a`
- `kubernetes.amazonaws.example/availability-zone-id: use1-az1`

**Comment by sftim** [comment]
`topology.k8s.aws/zone-id` is also fine as a label key; I hadn't seen that before.

**Comment by sftim** [comment]
/remove-lifecycle rotten

still seems relevant and referenced

**Comment by josh-ferrell** [comment]
> An alternative AWS-specific label could be `topology.k8s.aws/zone-id`
I'm in favor of this approach and possibly later adding the ability to configure CCM to populate `topology.kubernetes.io/zone` differently. I'll start looking into the first idea.

**Comment by rifelpet** [comment]
I asked in a sig-cloud-provider meeting around when I opened this issue and was told there is no equivalent concept in GCP and Azure.

**Comment by sayap** [comment]
OCI does it:

> To help balance capacity in data centers, Oracle Cloud Infrastructure randomizes availability domains by tenancy . For example, the availability domain labeled PHX-AD-1 for tenancyA might be a different data center than the one labeled PHX-AD-1 for tenancyB. 

(https://docs.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm)

**Comment by JoelSpeed** [comment]
So if we want to implement this feature, it might make sense to have it consistent across clouds that support it, to do that, we need to know that they expose a way for the CCM to set it. Do we know if oracle has an API similar to AWS?

What happens if the zone-id isn't needed for a platform, lets take Azure for example, if they don't do this, then `zone-id` isn't needed, we could set it to `zone` and duplicate the data, or omit it?

If omitted, then manifest examples might not work on platforms that omit it right?

**Comment by sayap** [comment]
@JoelSpeed You are talking specifically about `topology.kubernetes.io/zone-id`? https://github.com/kubernetes/cloud-provider-aws/issues/300#issuecomment-1568536231 proposed a way forward without setting this label.

**Comment by JoelSpeed** [comment]
@sayap Yes, I'm trying to work out if there's merit to having this as a standard kube well known label that would work across clouds, seems like if there is precedent for multiple clouds, having a consistent label name would be preferential to specific cloud having their own right?

**Comment by isugimpy** [comment]
Could this maybe be accomplished via opt-in using a flag on the binary to change `topology.kubernetes.io/zone` to the ID instead of the name?  That'd retain existing compatibility while allowing people to use the feature.

**Comment by mmerkes** [comment]
> I'm in favor of this approach and possibly later adding the ability to configure CCM to populate topology.kubernetes.io/zone differently. I'll start looking into the first idea.

@josh-ferrell [This something your working on?](https://github.com/kubernetes/cloud-provider-aws/issues/300#issuecomment-1568536231) Sounds reasonable to me.

**Comment by sftim** [comment]
@rifelpet I _think_ the consensus view is to use `topology.k8s.aws/zone-id` as the label key for the zone ID. If that looks right to you, would you be willing to update the issue description accordingly?

**Comment by rifelpet** [comment]
> @rifelpet I _think_ the consensus view is to use `topology.k8s.aws/zone-id` as the label key for the zone ID. If that looks right to you, would you be willing to update the issue description accordingly?

I've updated the issue description to match
