### ISSUE TITLE
Add support for e2e test and non-retryable error in the tagging controller

### ISSUE THREAD

**Issue by nguyenkndinh** [kubernetes/cloud-provider-aws#325]
**What would you like to be added**:
- Add e2e testing for tagging controller.
- Currently, all work items with errors from EC2 regarding tagging and untagging would be requeue to the workqueue. We would like to only requeue on transient errors.
Ref: https://github.com/kubernetes/cloud-provider-aws/pull/308#issuecomment-1082533927

**Why is this needed**:
- To have a comprehensive testing suite 
- To address a potential issue where failed jobs would stay in the queue indefinitely causing unnecessary calls to EC2.

/kind feature

**Comment by saurav-agarwalla** [comment]
> Currently, all work items with errors from EC2 regarding tagging and untagging would be requeue to the workqueue. We would like to only requeue on transient errors.

This AI is now complete.
