### ISSUE TITLE
helm chart: Using IRSA for cloud-provider-aws

### ISSUE THREAD

**Issue by jkroepke** [kubernetes/cloud-provider-aws#327]
**What would you like to be added**:

Hi, I would like to discuss if its useful to use [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) instead Instance profiles cloud-provider-aws. I would like reduce the permissions of an instance profile to an absolute minimum and use dedicated roles for each component.

In case this make sense, I can do a pull request to extend the helm chart.

Since control plane and non worker needs a [different set of permissions](https://cloud-provider-aws.sigs.k8s.io/prerequisites/), I suggest to split the existing DaemonSet into two. One for the control plane, one for worker node. Then I'm able to pass different service account tokens to different DaemonSets.

Before coding it, I would like ask, if someone is interest into it.

**Why is this needed**:
Increased security and traceability of IAM permissions. If the instance profile has close to zero permissions, no can abuse the permissions.

/kind feature

**Comment by olemarkus** [comment]
The DaemonSet will only run on the control plane by default. It shouldn't run on worker nodes at all.
E.g kOps will run CCM using IRSA, so this works as expected already.

The only thing needed is to configure volumes/env variables on the the Pods. Alternatively annotate the ServiceAccount if you use the Pod Identity Webhook.

**Comment by jkroepke** [comment]
What about the credential helper?

https://cloud-provider-aws.sigs.k8s.io/credential_provider/

I thought, it needs to be run on workers, too.

**Comment by olemarkus** [comment]
Credential helper is not a container. It must be installed as an executable on each node directly.
