### ISSUE TITLE
Incorrect YAML for kops overlay

### ISSUE THREAD

**Issue by jhohertz** [kubernetes/cloud-provider-aws#341]
https://github.com/kubernetes/cloud-provider-aws/blob/cc170f77cc8baaf5c4f75bfef9c2f9ef9b17ca7a/examples/kops-new-cluster/overlays/cloud-controller-manager/cluster.yaml#L15-L16

These two lines must be removed, or the CCM will not work correctly under kops in current versions at least.

@olemarkus mentioned it to me on [slack](https://kubernetes.slack.com/archives/C3QUFP0QM/p1649702861826179?thread_ts=1649692232.999669&cid=C3QUFP0QM) a little while ago, and thought I should mention it here.

**Comment by olemarkus** [comment]
Wondering if these overlays should be removed altogether. When setting `cloudControllerManager: {}` in the spec, or using k8s 1.24 and newer, kOps sets all the other flags correctly.
