### ISSUE TITLE
[Enhancement] specify static IPs for AWS existing Network load balancer

### ISSUE THREAD

**Issue by yang-wang11** [kubernetes/cloud-provider-aws#343]
I found the feature `specify static IPs for AWS Network load balancer` only available when creating a new NLB
https://github.com/kubernetes/kubernetes/blob/c1e69551be1a72f0f8db6778f20658199d3a686d/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L169-L174

However, I found the AWS official document already supports `Assign Elastic IP to an existing Network Load Balancer`. see below
https://aws.amazon.com/premiumsupport/knowledge-center/elb-attach-elastic-ip-to-public-nlb/

Should the team have a plan to enable this feature further?

**Comment by nckturner** [comment]
/triage accepted

We should either keep this NLB service controller up to date, or try to deprecate it/remove it completely.  For now, I'll triage this, and mention that you should consider running https://github.com/kubernetes-sigs/aws-load-balancer-controller/ which supports NLB services, new features and is maintained actively by an EKS team.

**Comment by yang-wang11** [comment]
@nckturner thanks for the information, I found only aws have its LB controller.  :<
as you know, [serviceController](https://github.com/kubernetes/kubernetes/tree/release-1.9/pkg/controller/service) is part of `CCM`,  it is really easy to use.  
I don't know whether is ok that enable `CCM` and `aws-load-balancer-controller` at the same time. is there any toggle to control whether to enable `serviceController`?
