### ISSUE TITLE
Node Addresses contain additional pod IPs with VPC CNI provider 

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/cloud-provider-aws#349]
Copied from https://github.com/aws/amazon-vpc-cni-k8s/issues/1983 which I determined is a CCM issue

**What happened**:
Kops' conformance tests are now failing when using k8s 1.24 and the AWS VPC CNI:

https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-amazon-vpc

Conformance tests that exercise nodeport functionality are failing.

**Attach Logs:**
See the a job's artifacts including all pod logs and other resource dumps: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/e2e-kops-aws-cni-amazon-vpc/1522414620394917888/artifacts/cluster-info/

**What you expected to happen:**
All conformance tests to pass

**How to reproduce it (as minimally and precisely as possible):**
Run the k8s 1.24 e2e tests on a k8s 1.24 cluster with `external` cloud provider and running the VPC CNI or anything that attaches additional IPs/ENIs to instances.

**Anything else we need to know?:**

The addresses of Nodes in k8s 1.23 with kubelet's `--cloud-provider=aws` only had the primary IPs for the instance. 

Kubelet uses what is passed in via `--node-ip` which kops sets as the only private IP found on the instance at instance-launch time. If this isn't set, kubelet falls back to trying instance metadata and or ec2.DescribeInstances to find all IPs attached to the instance but these fallbacks were never used. ([passing job example](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/13584/pull-kops-e2e-cni-amazonvpc/1521084135702007808/artifacts/cluster-info/nodes.yaml))

The addresses of Nodes in k8s 1.24 with kubelet's `--cloud-provider=external` have all IPs on the instance including the additional IPs that VPC CNI adds during tests ([failing job example](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/13609/pull-kops-e2e-cni-amazonvpc/1522408627636277248/artifacts/cluster-info/nodes.yaml)).

With --cloud-provider=external, [kubelet no longer sets the Node's addresses](https://github.com/kubernetes/kubernetes/blob/7e77252b0d5fcd3689f2f7e4a21757e53965c092/pkg/kubelet/nodestatus/setters.go#L97-L111), delegating the responsibility to CCM. [AWS CCM always uses ec2.DescribeInstances](https://github.com/kubernetes/cloud-provider-aws/blob/f17b3a858cd526d625869ac660736b85f77f0dc9/pkg/providers/v1/aws.go#L1530-L1590) to populate the addresses, resulting in the Node's addresses containing all of the IPs attached to the instance rather than just the primary IPs.

---

All of the failing e2e tests involve nodeport services, and one of the helper functions used in the e2e framework involves [getting the node objects](https://github.com/kubernetes/kubernetes/blob/5e9a6a256e9ed7834dfcf5f4a30be015130df6e9/test/e2e/framework/service/jig.go#L968-L999) and [testing whether the port is reachable on every internal IP](https://github.com/kubernetes/kubernetes/blob/5e9a6a256e9ed7834dfcf5f4a30be015130df6e9/test/e2e/framework/service/jig.go#L849-L870). This obviously fails for IPs that were added to the host for pods other than the pod under test since only the test pod's IP will be listening on the desired port.

Additionally, looking at the logs from any of the failing e2e tests show that it tries to connect to IPs that aren't associated with the destination pod but are associated with one of the instances. This also explains why the test failures vary between "connection refused" or "connection timed out"

**Environment**:
- Kubernetes version (use `kubectl version`): v1.24.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.13.0
- Install tools: kops
- Others:

/kind bug

**Comment by rifelpet** [comment]
[kubelet does set an annotation with the --node-ip it is provided](https://github.com/kubernetes/kubernetes/blob/7e77252b0d5fcd3689f2f7e4a21757e53965c092/pkg/kubelet/nodestatus/setters.go#L97-L103). Fixing this might be as simple as checking for that annotation first before trying `ec2.DescribeInstances`.

**Comment by olemarkus** [comment]
It looks like the tests are passing after we managed to get the 1.24/master branch of 1.24 running again. However, checking the annotation before doing the EC2 call seems like a good idea anyway.

**Comment by olemarkus** [comment]
Note, I can still reproduce this when testing locally. It just seems like the VPC IPs are added to node objects much slower.

**Comment by rifelpet** [comment]
I haven't stepped through the code yet to see how it fits with the addresses cloud-provider-aws returns, but [this](https://github.com/kubernetes/kubernetes/pull/107750/files) leads me to believe k8s.io/cloud-provider might be checking the kubelet node annotation already.

The node addresses are updated [every 5 minutes by default](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/cloud-provider/config/v1alpha1/defaults.go#L35-L37) and that hasn't changed recently. I wonder why the behavior has changed between 1.23 and 1.24/master ?

**Comment by olemarkus** [comment]
Good find. This came in with the k8s bump PR I did. So it resolved itself when we started using the non-stable image.

**Comment by olemarkus** [comment]
I think we can close this one as we do not see these errors anymore.

**Comment by whites11** [comment]
I face this problem using version 1.23.2, while I confirm it seems to be fixed in 1.24.
I can't find what PR fixed the wrong behaviour though, nor a related changelog entry in 1.24 releases.
Can you please help me understand?

**Comment by whites11** [comment]
> The fix is in the `k8s.io/cloud-provider` dependency as well as the kubelet code. So AWS CCM just indirectly fixes it by updating its dependencies :)

That explains it, thanks @olemarkus
