### ISSUE TITLE
Documentation: Links on Getting-Started page are out of date

### ISSUE THREAD

**Issue by mjbright** [kubernetes/cloud-provider-aws#385]
**What happened**:

I referred to the getting started page at https://kubernetes.github.io/cloud-provider-aws/getting_started/.

I tried to download the rbac.yaml referred to in the text:
```https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/master/manifests/rbac.yaml```

Same thing for
 ```https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/master/manifests/aws-cloud-controller-manager-daemonset.yaml```

**What you expected to happen**:
I expected
```https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/master/manifests/rbac.yaml```
and
```https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/master/manifests/aws-cloud-controller-manager-daemonset.yaml```
to be downloadable from the referenced URLs.

**How to reproduce it (as minimally and precisely as possible)**:

```wget https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/main/manifests/rbac.yaml```
```wget https://raw.githubusercontent.com/kubernetes/cloud-provider-aws/master/manifests/aws-cloud-controller-manager-daemonset.yaml```

**Anything else we need to know?**:
The URLs are no longer valid - it seems they have been moved and/orsplit into several files at: 

```https://github.com/kubernetes/cloud-provider-aws/tree/master/examples/existing-cluster/base```

**Environment**:
- Kubernetes version (use `kubectl version`): Not applicable ...
- Cloud provider or hardware configuration: Not applicable ...
- OS (e.g. from /etc/os-release): Not applicable ...
- Kernel (e.g. `uname -a`): Not applicable ...
- Install tools: Not applicable ...
- Others:

/kind bug

**Comment by jdboris** [comment]
Still a problem
