### ISSUE TITLE
Use Cross-Account Roles

### ISSUE THREAD

**Issue by bartelsb** [kubernetes/cloud-provider-aws#39]
**What would you like to be added**:
The ability to use [cross-account roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html) within my Kubernetes cluster.

**Why is this needed**:
I am managing a cluster in an AWS account that is not mine. I will soon not have credentials to that account. Instead, I will use a user from my own account to assume a role in the other account to perform any actions I need to in that account. I'd like the Kubernetes cluster to also assume a role for the purposes of managing load balancers and volumes. The alternative is that the role I assume has the ability to create and manage IAM users, which kind of defeats the purpose of using cross-account roles.

/kind feature

**Comment by micahhausler** [comment]
Hi @bartelsb, This repo isn't quite up to date and needs a note in the README as to the status, but in the upstream AWS cloudprovider, this is possible today.

You'll need to create a CloudConfig file, and set the [`RoleArn`](https://github.com/kubernetes/kubernetes/blob/v1.16.0-beta.1/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L560) field when you start the Kubernetes Controller Manager.
