### ISSUE TITLE
Where is the image for 1.22.3?

### ISSUE THREAD

**Issue by akunszt** [kubernetes/cloud-provider-aws#400]
**What happened**:
This is the first time I tried to deploy cloud-provider-aws. We're using Kubernetes 1.22 so I checked the last release in the 1.22 branch which was 1.22.3 at the time.
Unfortunately cloud-provider-aws uses registry.k8s.io which - as far as I know - doesn't have any UI and doesn't support image listing either. (I use lot of upstream registries and this is the worst/hardest to work with.)
I tried to fetch the image to test if it's really available. As you can see I tried with and without `v`.
```
~ $ docker pull registry.k8s.io/provider-aws/cloud-controller-manager:v1.22.3
Error response from daemon: manifest for registry.k8s.io/provider-aws/cloud-controller-manager:v1.22.3 not found: manifest unknown: Failed to fetch "v1.22.3" from request "/v2/provider-aws/cloud-controller-manager/manifests/v1.22.3".
~ $ docker pull registry.k8s.io/provider-aws/cloud-controller-manager:1.22.3
Error response from daemon: manifest for registry.k8s.io/provider-aws/cloud-controller-manager:1.22.3 not found: manifest unknown: Failed to fetch "1.22.3" from request "/v2/provider-aws/cloud-controller-manager/manifests/1.22.3".
```
I also tried to list the available tags but nothing found.
```
~ $ docker image ls -a registry.k8s.io/provider-aws/cloud-controller-manager 
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
```
Finally I tried to open the https://registry.k8s.io and https://registry.k8s.io/provider-aws/cloud-controller-manager but I received only 404.

Did I do something wrong or the 1.22.3 wasn't pushed to the registry at all? Is it possible to use a somewhat more user-friendly repository where we can actually see the available images?

**What you expected to happen**:
Image pulled correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Just try to pull the - assumed - URL of the 1.22.3 release.
```
docker pull registry.k8s.io/provider-aws/cloud-controller-manager:v1.22.3
```

**Anything else we need to know?**:
n/a

**Environment**:
(It doesn't matter in this case.)
- Kubernetes version (use `kubectl version`): 1.22.9
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Flatcar Linux 
- Kernel (e.g. `uname -a`): 5.10.102-flatcar
- Install tools: -
- Others: -

/kind bug

**Comment by akunszt** [comment]
I forget to add that I can fetch 1.22.2, 1.22.1 and 1.22.0. Only 1.22.3 is missing.

**Comment by olemarkus** [comment]
Unfortunately the release has been published without the images being promoted. Stay tuned and we'll get them published as soon as we can.

**Comment by akunszt** [comment]
Thanks, it is working. Do you have plans to use another registry in the future?
(This issue can be closed, I'm just curios.)

**Comment by olemarkus** [comment]
No. This registry is the correct one. The "problem" was that the release was published before the images were.
We'll take better care to ensure the images are available before the release are published the next time.
