### ISSUE TITLE
Missing image referenced in chart values & manifests for v1.21.2

### ISSUE THREAD

**Issue by DavidRayner** [kubernetes/cloud-provider-aws#410]
**What happened**:

Attempted deployment using manifests in the `v1.21.2` branch
The `cloud-controller-manager` image does not exist so the pod has `ImagePullBackOff`

**What you expected to happen**:

The app should run using the appropriate image

**How to reproduce it (as minimally and precisely as possible)**:

`docker pull gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.0-alpha.0`

**Anything else we need to know?**:

These images do exist:
 - registry.k8s.io/provider-aws/cloud-controller-manager:v1.21.0-alpha.0
 - registry.k8s.io/provider-aws/cloud-controller-manager:v1.21.1
 - registry.k8s.io/provider-aws/cloud-controller-manager:v1.21.2
 - gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.1
 - gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.21.2

Should the `appVersion` in `Chart.yaml` and image tags in `values.yaml` & manifests use the latest version `v1.21.2`?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.11

/kind bug

**Comment by hakman** [comment]
v1.21.2 image should be available now:
https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/provider-aws/cloud-controller-manager@sha256:454387af4fbfae72205b2b571a96bac2e35af6e1319c179207013b2a1ca5d510/details

**Comment by DavidRayner** [comment]
That image was available before I raised this issue. The problem is that `manifests/base/aws-cloud-controller-manager-daemonset.yaml` and `charts/aws-cloud-controller-manager/values.yaml` both reference an image tag that does not exist:

https://github.com/kubernetes/cloud-provider-aws/blob/release-1.21/manifests/base/aws-cloud-controller-manager-daemonset.yaml#L31
https://github.com/kubernetes/cloud-provider-aws/blob/release-1.21/charts/aws-cloud-controller-manager/values.yaml#L8
