### ISSUE TITLE
Wrong Target Type

### ISSUE THREAD

**Issue by zer0stars** [kubernetes/cloud-provider-aws#419]
Trying to use in tree aws provider with Ip based targets. Also, where can I find the logs for the in-tree provider? How can I force it to re-create the target groups?

**What happened**:
LoadBalancer targets get created with target type:instance. 

**What you expected to happen**:
Loadbalancer targets to get created with target type: ip

**How to reproduce it (as minimally and precisely as possible)**:
Create an NLB with following annotations:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: true
        service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: 120
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: false
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: 10
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: 6
**Anything else we need to know?**:
Nothing special about the environment.
**Environment**:
- Kubernetes version (use `kubectl version`):
  Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
  WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
- Cloud provider or hardware configuration:
AWS EKS - 1.22, 
- OS (e.g. from /etc/os-release):
AMI-1.7.2-28782dce
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by olemarkus** [comment]
This project is for the out-of-tree cloud-provider. When using EKS, the in-tree cloud provider is a part of the managed service, so a start may be to reach out to AWS support.

**Comment by kishorj** [comment]
@zer0stars, the CCM doesn't support IP targets. You'd need to install the external controller AWS Load Balancer Controller https://github.com/kubernetes-sigs/aws-load-balancer-controller/.

The annotation `service.beta.kubernetes.io/aws-load-balancer-type` needs to be `external`. Note: you need to create a new service with the external annotation, not edit `nlb` to `external`.

**Comment by olemarkus** [comment]
The feature you are asking for here only exists for [AWS Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/). CCM only supports instance targets.
