### ISSUE TITLE
How to run “cloud-provider-aws” application in local test

### ISSUE THREAD

**Issue by CaiNiaoHui** [kubernetes/cloud-provider-aws#427]
/triage support

I want to run the cloud-provider-aws 1.21.2 code in local for test. 
Now I am running the k8s cluster. And I have kube-config and aws account token stored in the local. 
I only set cloud-config parameters and --cloud-provider parameter, then I  run "cloud-provider-aws" program.
 as you know, it failed. The error log is "no configuration has been provided, try setting KUBERNETES_MASTER environment variable".
I have a question: What parameters do we need to configure if we need to run the application, and how should these parameters be set?

**Comment by CaiNiaoHui** [comment]
I install "cloud-provider-aws" plugin into the cluster by official helm chart package. I find some parameters need to set : this is log: 
![image](https://user-images.githubusercontent.com/29849201/175202649-c77b083a-48c7-4c54-b00e-022cabbec838.png)

**Comment by olemarkus** [comment]
Most of these flags should match the flags you set for kube-controller-manager.
