### ISSUE TITLE
Support for custom TagNameKubernetesClusterPrefix

### ISSUE THREAD

**Issue by jbonjean** [kubernetes/cloud-provider-aws#436]
**What would you like to be added**: A command line flag to override the default prefix (`kubernetes.io/cluster/`).

**Why is this needed**: The current value of the prefix is not compatible with [InstanceMetadataTags](https://aws.amazon.com/about-aws/whats-new/2022/01/instance-tags-amazon-ec2-instance-metadata-service/). Once this option is enabled, the regex for the tags on EC2 instances is not the same...

Error from the Auto Scaling group activity tab:
> Launching a new EC2 instance. Status Reason: 'kubernetes.io/cluster/my-cluster' is not a valid tag key. Tag keys must match pattern ([0-9a-zA-Z\\-_+=,.@:]{1,255}), and must not be a reserved name ('.', '..', '_index'). Launching EC2 instance failed.

/kind feature

**Comment by olemarkus** [comment]
How are you provisioning your cluster? The K8s ecosystem make heavy use of url-like tags. Also curious what you'd use instance metadata tags for.

**Comment by jbonjean** [comment]
Hey, not sure what you mean exactly by provisioning and how it's relevant, but it's a cloudformation that installs k3s via user-data.

I was experimenting with `InstanceMetadataTags` as a mean to pass additional information via tags to the instances, for example a "profile" tthat would determine if k3s-server or k3s-agent should be installed. It is still possible to access the tags with the `awscli`, but it's just less convenient and requires IAM permissions.

You're are right to say that the k8s ecosystem makes heavy use of url-like tags, and after thinking a bit more about it I don't think it's a good idea to enable this option as it could cause issue in the future with other components. I'm closing the issue.
