### ISSUE TITLE
AWS Cloud Providers in k8s usable sample/example

### ISSUE THREAD

**Issue by Vamsi51m** [kubernetes/cloud-provider-aws#44]
**Regarding the AWS Cloud Providers in k8s**

We are trying to use the cloud providers in the kubernetes 1.14.0 looks like we are there are a few issues in creating the cloud providers with the cluster.

Can we get a usable sample/example for AWS Cloud Providers in the k8s. Any help on this would be helpful.

**Comment by crazytaxii** [comment]
> **Regarding the AWS Cloud Providers in k8s**
> 
> We are trying to use the cloud providers in the kubernetes 1.14.0 looks like we are there are a few issues in creating the cloud providers with the cluster.
> 
> Can we get a usable sample/example for AWS Cloud Providers in the k8s. Any help on this would be helpful.

I am looking for an example too, find no such images and yaml files to use.
