### ISSUE TITLE
"cloud-controller-manager" continuously OOMKilled 

### ISSUE THREAD

**Issue by cathyzhang05** [kubernetes/cloud-provider-aws#440]
Hi team,

The Control Plan component "Cloud Controller Manager" for one cluster continuously failing to restart due to pod "cloud-controller-manager-*" OOMKilled.  The detail is shown below:
- After the maintenance time of the shoot cluster, the Control Plan components restarted, then the pod of cloud-controller-manager would be OOMKilled and can't be started again.
- Checked the memory for deployment cloud-controller-manager, it reached the maximum of memory limitation 2.6Gi.
The pod of cloud-controller-manager is in CrashLoopBackOff status.
<img width="1001" alt="Screen Shot 2022-08-16 at 15 23 56" src="https://user-images.githubusercontent.com/57243294/184821733-1432e806-2a81-4ade-8906-df85f81fc124.png">

- Restarted the cloud-controller-manager deployment, but the OOMKilled issue happened again without any suspicious error found.  Sometimes, the logs stopped at the "EnsuredLoadBalancer" step as shown:
```
{"log":"\"Event occurred\" object=\"XXXX" kind=\"Service\" apiVersion=\"v1\" type=\"Normal\" reason=\"EnsuredLoadBalancer\" message=\"Ensured load balancer\"","pid":"1","severity":"INFO","source":"event.go:294"}
```
- There are more than 110 nodes in this cluster, but I compared another cluster with more than 300 nodes which doesn't have the OOMKilled issue, the log is very similar when the pod started up. 

The cluster version information: 
- K8s: 1.23.4
- cloud-provider-aws: 1.24.0

Any idea or clue from your side?  Any more information you need, just let me know. Thank you. 

/triage support

**Comment by kon-angelo** [comment]
I am working with @cathyzhang05 and got this profile from one of the OOM runs:
[profile.pb.gz](https://github.com/kubernetes/cloud-provider-aws/files/9391954/profile.pb.gz). I hope this provides some extra data. To me it seems that the aws library has issues dealing efficiently with large API responses but I could be wrong. Have you seen that happen in the past ?
