### ISSUE TITLE
Introduce well-known tag for exclude subnets within a auto-discovery procedure for ELB backed services

### ISSUE THREAD

**Issue by lobziik** [kubernetes/cloud-provider-aws#442]
**What would you like to be added**:

Another well known tag for subnets which will helps to exclude subnets and prevent its attachment to an ELB during auto-discovery procedure.

or 

extend `kubernetes.io/role/elb` semantic and allow to specify `kubernetes.io/role/elb=0` for subnets exclusion.

**Why is this needed**:

Currently subnets auto-discovery procedure for ELB relies on `kubernetes.io/cluster/{clusterId}` and/or `kubernetes.io/role/elb` tags, however it might be desirable to not attach subnets in certain zones (local zones, wavelength zones) but still keep `kubernetes.io/cluster/{clusterId}` for another automation purposes. 

Some context (Openshift specific unfortunately): https://bugzilla.redhat.com/show_bug.cgi?id=2105337

/kind feature

**Comment by elmiko** [comment]
we have discussed this issue at the SIG Cloud Provider meeting on 31 August 2022.

follow up questions, 
* would this work need an enhancement to progress further?
* workaround might be specify load balancer on subnet, but this won't work necessarily in this situation.

/assign @kishorj 
/assign @nckturner

**Comment by lobziik** [comment]
I need to update patch after the kops changes was merged. But this issue is still actual.

/remove-lifecycle stale
