### ISSUE TITLE
Node Lifecycle Controller leaks node objects

### ISSUE THREAD

**Issue by saurav-agarwalla** [kubernetes/cloud-provider-aws#444]
**What happened**: The node lifecycle controller can leak node objects in cases where the controller is down for some time. This is because there are two scenarios that can happen when an underlying instance is terminated - for some time, EC2 returns the status of that instance as terminated in the `DescribeInstances` API call which is correctly handled [here](https://github.com/kubernetes/cloud-provider-aws/blob/1c6194aad0122ab44504de64187e3d1a7415b198/pkg/providers/v1/aws.go#L1708-L1712). But after some time has elapsed, the same API call will start returning `InvalidInstanceID.NotFound` which is where the bug surfaces. It seems, we wrap the error from EC2 [here](https://github.com/kubernetes/cloud-provider-aws/blob/1c6194aad0122ab44504de64187e3d1a7415b198/pkg/providers/v1/aws.go#L1007) which causes the check [here](https://github.com/kubernetes/cloud-provider-aws/blob/1c6194aad0122ab44504de64187e3d1a7415b198/pkg/providers/v1/aws.go#L1696-L1698) to fail since [this cast](https://github.com/kubernetes/cloud-provider-aws/blob/1c6194aad0122ab44504de64187e3d1a7415b198/pkg/providers/v1/aws.go#L1940) will never be true. Not wrapping the error should fix this issue.

**What you expected to happen**: I expect this code to handle `InvalidInstanceID.NotFound` gracefully.

**How to reproduce it (as minimally and precisely as possible)**: Create a dummy node object using `kubectl apply` with a non-existent instance ID. CCM logs would show an error instead of properly handling this case and deleting the node object.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by saurav-agarwalla** [comment]
The legacy provider also has the same bug - https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L974.

**Comment by olemarkus** [comment]
Nice find

/triage accepted

**Comment by saurav-agarwalla** [comment]
> Nice find
> 
> /triage accepted

Credit to @jyotimahapatra for finding the bug. 🙌
