### ISSUE TITLE
Dual-Stack support for NLB

### ISSUE THREAD

**Issue by rastislavs** [kubernetes/cloud-provider-aws#477]
**What would you like to be added**:
Support for dual-stack NLB LoadBalancer services. Already asked for in https://github.com/kubernetes/cloud-provider-aws/issues/243 before, but it seems not implemented.

**Why is this needed**:

[IPv4/IPv6 dual-stack feature](https://kubernetes.io/docs/concepts/services-networking/dual-stack/) is stable as of k8s 1.23. NLBs should be deployed with dual-stack / ipv6 enabled if indicated in `spec.ipFamilyPolicy` & `spec.ipFamilies`.

/kind feature

**Comment by olemarkus** [comment]
I do not believe the NLB support in CCM will be worked on further. Instead AWS load balancer controller should be used to provision such NLBs.

**Comment by rastislavs** [comment]
Looks like a very small change is needed. I am willing to contribute that if it still can be accepted.

**Comment by olemarkus** [comment]
Sure.

**Comment by kishorj** [comment]
@rastislavs, we already support dual-stack NLB/ IPv6 clusters via the external AWS Load Balancer controller - https://github.com/kubernetes-sigs/aws-load-balancer-controller/. Is there any reason you are unable to use the external controller?

**Comment by rastislavs** [comment]
> Is there any reason you are unable to use the external controller?

One of the reasons may be the complexity / missing documentation on how does the Cloud-Provider-AWS relate and deploys together with the AWS-Load-Balancer-Controller, so that the two controllers do not interfere etc. Given the existence of the https://github.com/kubernetes/cloud-provider-aws/issues/203 it seems that I am not the only one who is missing this clarification in the docs / READMEs.

My point is that if somebody is running a k8s cluster with Cloud-Provider-AWS and the existing capabilities are in general sufficient for them, then they would expect dual-stack to work as well (as it is now GA in upstream k8s). The change for adding that support is not big at all: https://github.com/kubernetes/cloud-provider-aws/pull/497

**Comment by olemarkus** [comment]
I think the confusion between LBC and CCM need to be resolved sometime soon. CCMs in general sort of requires a service controller, and if it's discouraged to use NLBs with the CCM service controller then perhaps LBC should be considered a part of CCM (at least the NLB part). And the CCM instructions should advice installing LBC or even bundle it.

This also takes care of an issue where CCM is required to provide load balancers for services that have no class defined, while many users would appreciate that LBC provides the default implementation.

**Comment by james-callahan** [comment]
> I think the confusion between LBC and CCM need to be resolved sometime soon. CCMs in general sort of requires a service controller, and if it's discouraged to use NLBs with the CCM service controller then perhaps LBC should be considered a part of CCM (at least the NLB part). And the CCM instructions should advice installing LBC or even bundle it.

I was likewise confused by this today.
Could LBC be integrated into CCM?

As an aside, there is also an ACK controller that creates/manages ELBs. AWS have far too many ways to manage the same resources.
