### ISSUE TITLE
What is the plan to migrate existing clusters from in-tree to out-of-tree CPI?

### ISSUE THREAD

**Issue by wangyuan0916** [kubernetes/cloud-provider-aws#501]
I'm planning to migrate existing k8s clusters on aws from in-tree to out-of-tree CPI in our product, and trying to figure out the process and the timeline. According to [KEP 2395](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers#removing-in-tree-cloud-provider-code), in Phase 3, "A plan to migrate existing clusters from using the kube-controller-manager to the cloud-controller-manager is currently being developed." Is it the newest status of aws? I guess yes because I didn't find any guide about this...
The second question is, in [KEP 2395](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers#removing-in-tree-cloud-provider-code), in Phase 4, I noticed two feature gates DisableCloudProviders and DisableKubeletCloudCredentialProvider are provided, and when in GA stage, we should finished migrating from in-tree to out-of-tree. For my understanding, this is the deadline of migration. One release after GA, the in-tree code will be removed. Please correct me if I'm wrong. Will aws follow this process? I heard some cloud providers will remove code before the two feature gates GA, so I'd like to make it clear on aws.
Third, is there any info about the overall timeline about when migration plan is ready , when we cannot use in-tree cpi, when to remove code....?
Thanks!

**Comment by olemarkus** [comment]
There are two approaches mentioned here: https://cloud-provider-aws.sigs.k8s.io/getting_started/
This is if your cluster is very self-managed. If you use an installed, most likely the installer will handle the transition transparently. kOps has already migrated for clusters >= 1.24.

**Comment by wangyuan0916** [comment]
Thanks @olemarkus! You're very helpful! Do you know the deadline of using in-tree CPI? There're 2 dates related, one is DisableCloudProviders and DisableKubeletCloudCredentialProvider GA, second is the in-tree code removal.

**Comment by olemarkus** [comment]
They have been planned and encouraged for quite some time already. Just like we've seen with EBS CSI driver, I think the actual release for code removal will keep being pushed a few years before it actually happens.

That being said, CCM already has a large number of fixes that won't make it to in-tree, so the sooner you migrate, the better experience you will be getting.
