### ISSUE TITLE
NLB HealthCheckIntervalSeconds cannot be overridden with annotations

### ISSUE THREAD

**Issue by krish7919** [kubernetes/cloud-provider-aws#51]
**What happened**:
The docs and the code [here](const ServiceAnnotationLoadBalancerHCInterval = "service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval") clearly state that we can use annotations to override the healthcheck interval:

```
// ServiceAnnotationLoadBalancerHCInterval is the annotation used on the
// service to specify, in seconds, the interval between health checks.
const ServiceAnnotationLoadBalancerHCInterval = "service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval"
```

**What you expected to happen**:

When I set the annotation to, for example, `5`, I want the healthchecks to happen every 5 seconds.

**How to reproduce it (as minimally and precisely as possible)**:
Create a service of type `LoadBalancer` with the NLB annotation in AWS.

**Anything else we need to know?**:
[This code](https://github.com/kubernetes/cloud-provider-aws/blob/8f6e1e3d2cfa20a0deac088b9c4022d433500369/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L390-L400) sets the default `HealthCheckIntervalSeconds` to `30` seconds, which is then never over-written by the user provided value.

```
		input := &elbv2.CreateTargetGroupInput{
			VpcId:                      aws.String(vpcID),
			Name:                       aws.String(name),
			Port:                       aws.Int64(mapping.TrafficPort),
			Protocol:                   aws.String("TCP"),
			TargetType:                 aws.String("instance"),
			HealthCheckIntervalSeconds: aws.Int64(30),
			HealthCheckPort:            aws.String("traffic-port"),
			HealthCheckProtocol:        aws.String("TCP"),
			HealthyThresholdCount:      aws.Int64(3),
			UnhealthyThresholdCount:    aws.Int64(3),
		}
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.9
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from /etc/os-release): Amazon Linux

/kind bug

**Comment by krish7919** [comment]
I can submit a PR to fix this, if there is a reason why this is not overridden by the user defined value; if there is a design document discussing it.

**Comment by krish7919** [comment]
sig-network

**Comment by krish7919** [comment]
@jsafrane can you please mention the right folks here, if possible. Thanks!

**Comment by jsafrane** [comment]
> @jsafrane can you please mention the right folks here, if possible. Thanks!

I believe @mcrute and @nckturner are the right people

**Comment by krish7919** [comment]
I was going through the AWS docs about this and it seems one cannot change it if the protocol is TCP, and AWS mandates the health check interval to be 30 seconds. :(

From the docs at: https://docs.aws.amazon.com/cli/latest/reference/elbv2/modify-target-group.html

```
--health-check-interval-seconds (integer)

The approximate amount of time, in seconds, between health checks of an individual target. For Application Load Balancers, the range is 5 to 300 seconds. For Network Load Balancers, the supported values are 10 or 30 seconds.

If the protocol of the target group is TCP, you can't modify this setting.
```

**Comment by krish7919** [comment]
Would a PR help here?

And can it be backported to v1.11.9 which is being used by EKS?

**Comment by krish7919** [comment]
Opened a corresponding issues in k8s repo [here](https://github.com/kubernetes/kubernetes/issues/81469).

**Comment by krish7919** [comment]
Is there an update on this?

**Comment by krish7919** [comment]
Is there an update on this?

**Comment by halcyondude** [comment]
Hello, we are hitting this issue as well.

**Comment by halcyondude** [comment]
+1

**Comment by nckturner** [comment]
@kishorj @M00nF1sh

**Comment by krish7919** [comment]
Bump?
