### ISSUE TITLE
Docker Images missing?

### ISSUE THREAD

**Issue by xrstf** [kubernetes/cloud-provider-aws#521]
**What happened**:
I tried to update the CCM in our clusters and noticed that none of the tags from October 4th (1.24.2, 1.23.5, 1.22.6, 1.21.5) are available as Docker images. Neither `k8s.gcr.io/provider-aws/cloud-controller-manager:v1.24.2` nor `registry.k8s.io/provider-aws/cloud-controller-manager:v1.24.2` exist

**What you expected to happen**:
I would have expected the images to be available a week after the tags were set.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
docker pull registry.k8s.io/provider-aws/cloud-controller-manager:v1.24.2
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others:

/kind bug

**Comment by xmudrii** [comment]
It looks like that images are pushed to the staging repo, but aren't promoted. For example, `skopeo inspect --raw docker://gcr.io/k8s-staging-provider-aws/cloud-controller-manager:v1.24.2` finds the image in the staging registry.

Is it possible to get those tags promoted? I think the following tags are affected:

* v1.24.2
* v1.23.3 - v1.23.5
* v1.22.5 and v1.22.6

cc-ing some folks for awareness
@olemarkus @andrewsykim

**Comment by xrstf** [comment]
New images have since been published and the state of older Kubernetes releases is not important anymore, I'd guess.
