### ISSUE TITLE
V1 provider's isRegionValue suppresses EC2 metadata errors

### ISSUE THREAD

**Issue by jasdel** [kubernetes/cloud-provider-aws#524]
**What would you like to be added**:

The v1's [isRegionValid](https://github.com/kubernetes/cloud-provider-aws/blob/704b05de2c8633e4acaae62bd81c5575e1e5c1d6/pkg/providers/v1/aws.go#L1449) does not return an error value. This means that if the ec2metadata client failed to make an API call to the EC2 metadata service the error will be suppressed, and `false` returned. [newAWSCloud](https://github.com/kubernetes/cloud-provider-aws/blob/704b05de2c8633e4acaae62bd81c5575e1e5c1d6/pkg/providers/v1/aws.go#L1349-L1353) interprets any `false` return of `isRegionValid` as `not a valid AWS zone` error.

**Why is this needed**:

Lack of error value propagation of `isRegionValid` creates confusing error messages about the region not being valid, even though the underlying issue may be that the provider wasn't able to communicate with the EC2 metadata service.

/kind feature

**Comment by jaypipes** [comment]
@jasdel Yeah, I'd noticed the same and failed to submit a patch that addressed this. Are you planning on submitting a corresponding patch or should I?

**Comment by jasdel** [comment]
Thanks @jaypipes yeah I'll put together a PR for this. Its a pretty small change I think.
