### ISSUE TITLE
Retrieve AWS Region from EC2 Metadata service directly 

### ISSUE THREAD

**Issue by jasdel** [kubernetes/cloud-provider-aws#525]
**What would you like to be added**:

The way the [v1](https://github.com/kubernetes/cloud-provider-aws/blob/704b05de2c8633e4acaae62bd81c5575e1e5c1d6/pkg/providers/v1/aws.go#L1349-L1353) and [v2]() AWS providers validate and retrieve the AWS Region could be improved to request the region value directly from EC2 metadata instance via the [EC2Metadata.Region](https://pkg.go.dev/github.com/aws/aws-sdk-go/aws/ec2metadata#EC2Metadata.Region) method, or both region and AZ at once via [EC2Metadata.GetInstanceIdentityDocument](https://pkg.go.dev/github.com/aws/aws-sdk-go/aws/ec2metadata#EC2Metadata.GetInstanceIdentityDocument). This would reduce the need to parse the AZ into an AWS region.

* v1 [isRegionValid](https://github.com/kubernetes/cloud-provider-aws/blob/704b05de2c8633e4acaae62bd81c5575e1e5c1d6/pkg/providers/v1/aws.go#L5230-L5248)
* v1 [getRegionFromMetadata](https://github.com/kubernetes/cloud-provider-aws/blob/704b05de2c8633e4acaae62bd81c5575e1e5c1d6/pkg/providers/v1/aws.go#L1449-L1477)

**Why is this needed**:

Updating the providers to request Region and AZ directly from EC2 Metadata and not parse the values helps improve the robustness of the provider by removing domain knowledge of AZ and AWS Region value format.

/kind feature

**Comment by jaypipes** [comment]
@jasdel seems very reasonable to me. ++

**Comment by dims** [comment]
@jasdel +1 to the proposal!
