### ISSUE TITLE
NLB resource leak after changing service type from LoadBalancer to ClusterIP

### ISSUE THREAD

**Issue by hanlins** [kubernetes/cloud-provider-aws#528]
**What happened**:
The NLB related resource is leaked after changing service type from LoadBalancer to ClusterIP.

**What you expected to happen**:
The NLB related resource should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Create a service of `LoadBalanver` type, then change the service type to `ClusterIP`. After the change is done, check the aws console and we see the load balancer resource is left.

**Anything else we need to know?**:
Tested that [`aws-load-balancer-controller`](https://github.com/kubernetes-sigs/aws-load-balancer-controller) supports removing NLB after changing the service type from `LoadBalancer` to `ClusterIP`. The inconsistent behavior is confusing for AWS users.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by emiljanogj** [comment]
Hi @hanlins, is this issue suitable for a first-time contributor? If yes, can I start working on it?

**Comment by hanlins** [comment]
> Hi @hanlins, is this issue suitable for a first-time contributor? If yes, can I start working on it?

Hi @emiljanogj, thanks for stopping out! Go ahead and let me know if you need my supports on the fix.

**Comment by JoelSpeed** [comment]
@hanlins Do you happen to know what version of Kubernetes you were running when you saw this? And do you know if this was happening before or whether this is a regression from a previously working behaviour?
