### ISSUE TITLE
Sync node labels to EC2 instances

### ISSUE THREAD

**Issue by hanlins** [kubernetes/cloud-provider-aws#560]
**What would you like to be added**:
Currently, tagging controller will tag all EC2 instances joining the cluster with some static tagging when initializing the tagging controller:
https://github.com/kubernetes/cloud-provider-aws/blob/c7e292ecc671d2cce2c5680393183d7034812f56/pkg/controllers/tagging/tagging_controller.go#L91-L136
(and then the same `tc.tags` is applied to all EC2 instances in the cluster)
https://github.com/kubernetes/cloud-provider-aws/blob/c7e292ecc671d2cce2c5680393183d7034812f56/pkg/controllers/tagging/tagging_controller.go#L281-L308
We would like a mechanism to sync some node labels to EC2 instances on a per-node basis.

**Why is this needed**:
We're deploying tenants' workloads using k8s and we leverage AWS tagging on EC2 instances for billing. Currently, the tenancy model is one tenant per k8s cluster, so it's ok to apply the same set of tagging for all EC2 instances in the same k8s cluster since the billing goes to the same tenant. However, with the increment of tenants, we run short of k8s clusters and we want to improve the utilization of k8s clusters by making k8s shared by multiple tenants since each tenant only requires a few nodes. In this case, we want to bill nodes within the same k8s cluster differently since the bill goes to different tenants. If we have a mechanism to sync labels to EC2 tagging on a per-node basis, then that would be a great help, otherwise we would need some other mechanism to tag EC2 instances directly.

/kind feature

**Comment by hanlins** [comment]
This requirement is pretty common for third-party software vendors using the public cloud. Let me know if this makes sense, and would be willing to help with the implementation😄

**Comment by olemarkus** [comment]
Would you not be able to handle this more easily on the ASG/node group/instance group level? Have one set of ASGs per tenant for example?

**Comment by hanlins** [comment]
Hi @olemarkus, thanks for the quick response!
> Would you not be able to handle this more easily on the ASG/node group/instance group level? Have one set of ASGs per tenant for example?

Unfortunately no in our case. We're using EKS together with managed node groups and the default node groups count per EKS cluster quota is 30 by default. Our system has multiple components (let's say five) and each takes a dedicated node group (since each component might need a different instance type or settings). Let's say in a typical 3AZ deployment, we need at minimum 15 node groups. If the label is applied on ASG or node group, then we need 15 NGs per-tenant, that can easily use up the quota (we tried to increase the quota to 300 previously but failed). That said, we want to make tenants shared the node groups :)

**Comment by olemarkus** [comment]
I see. I am a little bit concerned about the reconciliation needs for something like this. Tagging controller doesn't really support it, and personally, I don't think CCM is the right place for this. You may be better off writing a custom controller. Wouldn't even be that much of work.

**Comment by hanlins** [comment]
In terms of implementation, one feasible approach IMO is to introduce a new `labels` parameter which takes a list of label keys that I intended to sync from k8s objects to AWS resources. When applying tags (e.g. in `tagEc2Instance`), look for the set of labels in a best-effort way from k8s objects, and merge them with `tc.tags` before `tc.cloud.TagResource`.
https://github.com/kubernetes/cloud-provider-aws/blob/c7e292ecc671d2cce2c5680393183d7034812f56/pkg/controllers/tagging/tagging_controller.go#L281-L308
Wouldn't be super complicated in terms of implementation.

Well, it's true that it wouldn't be a huge load of work to implement a separate controller just for tagging, but it might be challenging for debugging and maintaining since the resource tagging logic is scattered into different components. People might need to tell whether the tag is from CCM or the customized tagging controller. It would be great if we can unify the resource tagging logic and configuration in one place, and since CCM already supports global resource tagging (i.e. tag resources using the tags in configuration), I'm leaning towards making CCM also supports customized label-based tagging.

**Comment by olemarkus** [comment]
I think you absolutely need to bring your own tag prefix into something like this anyway, so you should be able to tell the origin of the tags based on that. There are already other controllers that do custom tagging of various resources.
