### ISSUE TITLE
ExternalIP, DNS names only included in node addresses for ipv4 family

### ISSUE THREAD

**Issue by cartermckinnon** [kubernetes/cloud-provider-aws#577]
**What happened**:

If CCM is configured with:
```
NodeIPFamilies:
- ipv6
```
no `ExternalIP`, `InternalDNS`, or `ExternalDNS` addresses are added to the `Node`.

These addresses are only added when `ipv4` is present in `NodeIPFamilies`. However, `ipv4` results in an IPv4 `InternalIP` being added as well, which is not the desired behavior for an IPv6 EKS cluster. Hence a configuration like this does not achieve the desired behavior:
```
NodeIPFamilies:
- ipv6
- ipv4
```

The behavior differs from the (now removed) in-tree provider, which used the IP of the `eth0` device as it's `InternalIP` (either IPv4 or IPv6) and used `public-ipv4` from IMDS as it's `ExternalIP`. The DNS name logic is the same, but it's landed in the `ipv4`-only path of the external cloud provider.

Reference: https://github.com/kubernetes/legacy-cloud-providers/blob/23e4bd51a40a06ffc79b40d4fbc452c050eaeff7/aws/aws.go#L1500

**What you expected to happen**:

When `NodeIPFamilies` contains only `ipv6`:
- `InternalIP` should be an IPv6 address.
- `ExternalIP` should be an IPv4 address.
- `InternalDNS` and `ExternalDNS` should be present.

When `NodeIPFamilies` contains only `ipv4`:
- `InternalIP` should be an IPv4 address.
- `ExternalIP` should be an IPv4 address.
- `InternalDNS` and `ExternalDNS` should be present.

When `NodeIPFamilies` contains both `ipv4` and `ipv6`:
- This configuration is currently out of scope for EKS; we plan to use the control plane's `KubernetesVersionConfig::IpFamily` as the only value in `NodeIPFamilies`.

**How to reproduce it (as minimally and precisely as possible)**:

Create an EKS cluster on, e.g. 1.25.

Run CCM with:
```
NodeIPFamilies:
- ipv6
```

Use `--cloud-provider=external` on kubelet.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.25.6, 1.26.1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Amazon Linux 2

/kind bug

**Comment by cartermckinnon** [comment]
I'll put a PR together once I work through the details a bit more; the ramifications of this behavior change isn't immediately clear to me. I assume things like ingress controllers rely on the `ExternalIP`, for example.

**Comment by olemarkus** [comment]
The current behavior is the correct behavior. If `NodeIPFamilies` contains only `ipv6`, the cluster essentially doesn't have a concept of IPv4. Nodes may have received an IPv4 address from the VPC, but it shouldn't be exposed to the cluster components in any way.

The difference between `InternalIP` and `ExternalIP` is whether the cluster should use the IP for node-to-node communication or not. There is no expectation that `InternalIP` is only internal to the cluster. In IPv6 K8s clusters using publicly routable IPs, the cluster therefore only has `InternalIP` because there are no IPs that _shouldn't_ be used for node-to-node communication.

**Comment by cartermckinnon** [comment]
Thanks @olemarkus! Makes sense to me.

Are the internal/external DNS addresses intended to be omitted with the external provider?

**Comment by olemarkus** [comment]
That may be related to resource based naming. For IPv6 we could set these as before, but I am not sure how useful they are.

**Comment by cartermckinnon** [comment]
Closing this as the behavior is expected.
