### ISSUE TITLE
How to provide cluster-name?

### ISSUE THREAD

**Issue by camaeel** [kubernetes/cloud-provider-aws#590]
I set up aws-cloud-controller-manager with flag --cluster-name=customName, but the application still detects the cluster name automatically from the node it is running on. Is there any way to either make it run this flag, or provide it through --cluster-config file (an example of such file would be appreciated).

/triage support

**Comment by olemarkus** [comment]
What do you mean by that it detects cluster name from the node it runs on?

**Comment by camaeel** [comment]
@olemarkus I mean that it queries AWS (IMHO IMDS) and checks what are the tags of the instance it runs on. THen it assumes the whole cluster uses those, and completely ignores cluster-name flag. This is at least misleading, that such parameter might be supported.

**Comment by olemarkus** [comment]
Right. It seems this flag isn't being consumed at all. Instead it uses `KubernetesClusterID` under the `[global]` section of cloud-config. This fairly close to a bug.

**Comment by camaeel** [comment]
@olemarkus Do you maybe to have a working example of correct cloud-config file?

**Comment by olemarkus** [comment]
Not using this one. But it's standard ini-file stuff. So this probably works:

```
[global]
KubernetesClusterID=<clustername>
KubernetesClusterTag=<clustername>
```

**Comment by camaeel** [comment]
Thanx @olemarkus 
I tried both yaml and json :D.

**Comment by cartermckinnon** [comment]
The `--cluster-name` flag maps to:
```
k8s.io/cloud-provider/app/config.CompletedConfig.ComponentConfig.KubeCloudShared.ClusterName
```

> that it queries AWS (IMHO IMDS) and checks what are the tags of the instance it runs on.

Which controller has this behavior?

**Comment by olemarkus** [comment]
It's the whole provider that does this. So I'd think this affects all controllers.
