### ISSUE TITLE
Behavior change querying node name when using Resource Based Naming

### ISSUE THREAD

**Issue by stmcginnis** [kubernetes/cloud-provider-aws#595]
**What happened**:

Noticing this with Bottlerocket when going from k8s 1.25, which used the in-tree cloud provider, to 1.26 that switches to using the out-of-tree provider.

With the in-tree provider, the cloud provider would [set the host name to `PrivateDnsName` from doing a `DescibeInstances` call](https://github.com/awslabs/amazon-eks-ami/issues/1263#issuecomment-1507685282).

Now with the out-of-tree provider, without resource based naming being used the EC2 API call would get something like `ip-xx-xx-xx.us-west-2.compute.internal` and things work fine for registering a new node.

With resource based naming though, the EC2 API call returns something like `i-12344abdbc.us-west-2.compute.internal` and joining the cluster fails with:

```
Apr 14 16:50:34 kubelet[1183]: I0414 16:50:34.512901    1183 kubelet_node_status.go:70] "Attempting to register node" node="ip-192-168-11-149.us-west-2.compute.internal"
Apr 14 16:50:34 kubelet[1183]: E0414 16:50:34.514677    1183 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes \"ip-192-168-11-149.us-west-2.compute.internal\" is forbidden: node \"i-08f5eefc38f9c6289.us-west-2.compute.internal\" is not allowed to modify node \"ip-192-168-11-149.us-west-2.compute.internal\"" node="ip-192-168-11-149.us-west-2.compute.internal" 
```

The workaround with something like Amazon Linux from the linked issue comment above is to pass `--hostname-override` to match. With Bottlerocket that isn't really an option since the user or script (terraform or whatever is being used) would need to know the name beforehand.

**What you expected to happen**:

Expected behavior to be consistent with the in-tree provider and get the correct hostname to use.

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to join a Bottlerocket aws-k8s-1.26 node to a cluster inside a subnet configured to use "Hostname type: Resource Name".

**Anything else we need to know?**:

A lot of background and troubleshooting captured in https://github.com/bottlerocket-os/bottlerocket/issues/3013

**Environment**:
- Kubernetes version (use `kubectl version`): 1.26
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): `Bottlerocket OS 1.13.2 (aws-k8s-1.26)`
- Kernel (e.g. `uname -a`): `5.15.90`
- Install tools:
- Others:

/kind bug

**Comment by stmcginnis** [comment]
Possibly better, or at least more concise, description of the behavior change observed here: https://github.com/bottlerocket-os/bottlerocket/issues/3013#issuecomment-1509119669

**Comment by olemarkus** [comment]
Out of tree and in-tree provider has deliberately different behavior here because out-of-tree provider does use the instance metadata api to get node information. See https://cloud-provider-aws.sigs.k8s.io/prerequisites/

**Comment by stmcginnis** [comment]
Thanks for the pointer @olemarkus. I guess that makes sense. It's unfortunate their is a behavioral change between in and out of tree providers, but I guess it's just something that will need to be adjusted for.

/close
