### ISSUE TITLE
ecr-credential-provider fails with Kubelet 1.27

### ISSUE THREAD

**Issue by ikolomiyets** [kubernetes/cloud-provider-aws#596]
**What happened**:
ecr-credentials-provider deployed to managed k8s cluster fails to produce credentials.
Following errors appeared in the logs:
`E0415 17:54:20.388462   20666 plugin.go:233] Failed getting credential from external registry credential provider: error execing credential provider plugin ecr-credential-provider for image xxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/xxxxxxxxx: exit status 1`

**What you expected to happen**:
We expected kubelet to be able to get ECR credentials and pull required image

**How to reproduce it (as minimally and precisely as possible)**:
The ecr-credential-provider binary installed on the worker node in /usr/local/bin directory.

Credential provider config file /var/lib/kubernetes/ecr-credential-provider-config.yaml created with the following content:
```
kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1
providers:
  - name: ecr-credential-provider
    apiVersion: credentialprovider.kubelet.k8s.io/v1
    matchImages:
      - "*.dkr.ecr.*.amazonaws.com"
    defaultCacheDuration: 1m
```
Kubelet configured with the following parameters:
```
  --image-credential-provider-bin-dir=/usr/local/bin \
  --image-credential-provider-config=/var/lib/kubernetes/ecr-credential-provider-config.yaml \
```

**Anything else we need to know?**:
Further investigation shown that it fails validating the GroupName. The following code accepts only the `credentialprovider.kubelet.k8s.io/v1alpha1` apiVersion.
```
	if gvk.GroupVersion() != v1alpha1.SchemeGroupVersion {
		return fmt.Errorf("group version %s is not supported", gvk.GroupVersion())
	}
```

However, since kubernetes 1.26 APIs [were updated to v1](https://github.com/kubernetes/kubernetes/pull/111616) (although with no API changes).

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:42Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`): `Linux ip-10-0-xxx-xxx.eu-west-1.compute.internal 5.10.176-157.645.amzn2.x86_64 #1 SMP Tue Mar 28 17:49:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

/kind bug

**Comment by dims** [comment]
xref: https://github.com/kubernetes/cloud-provider-aws/pull/597

**Comment by cartermckinnon** [comment]
@olemarkus this can be closed 😄
