### ISSUE TITLE
NLBs don't seem to support tagging

### ISSUE THREAD

**Issue by philandstuff** [kubernetes/cloud-provider-aws#60]
**What happened**: I created a Service with `service.beta.kubernetes.io/aws-load-balancer-type: nlb` and `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=sandbox-main,Name=sandbox-main-ingress`.

**What you expected to happen**: I expected to get an NLB with the given tags. Instead I got an NLB with no tags.

**How to reproduce it (as minimally and precisely as possible)**: Create a Service as described above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:57:54Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS on EKS
- OS (e.g. from /etc/os-release): Amazon Linux
- Kernel (e.g. `uname -a`): whatever the EKS-optimized AMI provides
- Install tools:
- Others:

/kind bug

**Comment by kapilt** [comment]
i was curious and looked at the source, afaics it does support creating the nlb tags and target group tags (https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L131), and your annotation is correct
