### ISSUE TITLE
Enable Authenticated ECR Public Repo 

### ISSUE THREAD

**Issue by TebogoAWS** [kubernetes/cloud-provider-aws#602]
**What would you like to be added**:

Enhance ecr-credential-provider to authenticate to ECR Public repositories.
Currently we only looking at the [private repository pattern](https://github.com/kubernetes/cloud-provider-aws/blob/261c1231b669bc378d13c14e33049ac31b5e1b78/cmd/ecr-credential-provider/main.go#L39)

>var ecrPattern = regexp.MustCompile(`^(\d{12})\.dkr\.ecr(\-fips)?\.([a-zA-Z0-9][a-zA-Z0-9-_]*)\.(amazonaws\.com(\.cn)?|sc2s\.sgov\.gov|c2s\.ic\.gov)$`)

**Why is this needed**:

Customers who are doing numerous anonymous pull requests from ECR Public repositories will hit the data transfer limit of 500 GB.
Thereafter, they would need to authenticate before they would be able to do any further pulls.

[Data transferred from public repositories:](https://aws.amazon.com/ecr/pricing/)

<html>
<body>

Data Transfer OUT *** |  
-- | --
Without using an AWS Account |  
500 GB / month | $0.00 per GB
When using an AWS Account |  
5 TB / month

</body>
</html>

On k8s this means implementing a process where nodes would have to authenticate manually i.e. CronJob and scheduling it to reauthenticate within 12 hours to get a new token.

A seamless approach would be to add the public repository pattern and update the match image pattern in [kubelet configuration](https://github.com/awslabs/amazon-eks-ami/blob/master/files/ecr-credential-provider-config.json)

/kind feature

**Comment by mmerkes** [comment]
I'm looking at putting up a PR for this. [We get the region from the ECR URL](https://github.com/kubernetes/cloud-provider-aws/blob/261c1231b669bc378d13c14e33049ac31b5e1b78/cmd/ecr-credential-provider/main.go#L51-L54), which won't work for a public repository, so we'll need an alternate mechanism to get the region.

**Comment by mmerkes** [comment]
It will actually be a little different still. Public ECR registries require you to authenticate in us-east-1 and require different tokens from the private repositories, so we'll have to use two different credential providers and tokens based on the registry.
