### ISSUE TITLE
Promote registry.k8s.io/provider-aws/cloud-controller-manager images for v1.27.2, v1.23.7, v1.22.8, v1.21.7

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/cloud-provider-aws#620]
**What happened**:
`registry.k8s.io/provider-aws/cloud-controller-manager` (ref https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-provider-aws/images.yaml#L63-L101) is currently missing the tags v1.27.2, v1.23.7, v1.22.8, v1.21.7 which are available in the staging repo (ref https://console.cloud.google.com/gcr/images/k8s-staging-provider-aws/global/cloud-controller-manager).
We would appreciate if you can promote the above-mentioned tags.

**What you expected to happen**:
The above-mentioned tags to be available in `registry.k8s.io/provider-aws/cloud-controller-manager`.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

```
% docker pull registry.k8s.io/provider-aws/cloud-controller-manager:v1.27.2
Error response from daemon: manifest for registry.k8s.io/provider-aws/cloud-controller-manager:v1.27.2 not found: manifest unknown: Failed to fetch "v1.27.2"
```

while such tag exists for this repo - ref https://github.com/kubernetes/cloud-provider-aws/releases/tag/v1.27.2

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by cartermckinnon** [comment]
Closed by https://github.com/kubernetes/k8s.io/pull/5657

/close
