### ISSUE TITLE
Error fetching instance-id from ec2 metadata service

### ISSUE THREAD

**Issue by ranjithvasireddy** [kubernetes/cloud-provider-aws#625]
Hello Team, 

# Error fetching instance-id from ec2 metadata service from IMDS-V2 enabled Instances in AWS Kubenrets Nodes

# No issue if we disable the IMDS-V2  for Ec2 Instances

We are started working recently to Update all our  **EC2**  Instances to use  **IMDS-V2** service. After we enable them, **Kubelet** is started failing with few errors saying that It's unable to query the AWS Metadata from the instance. Since, we have updated the IMDS-V2 for all our Instances, how do we pass the Token to Kubelet to use Token Based Authentication to fetch all the metadata values ? or how to we send the few required values to Kubelet from cloud-provider config file.

# Error from Kubelet log:
WARNING: aws built-in cloud provider is now deprecated. The AWS provider is deprecated and will be removed in a future release
Building AWS cloudprovider
failed to run Kubelet: could not init cloud provider "aws": error fetching instance-id from ec2 metadata service: "EC2MetadataError: failed to make EC2Metadata request\ncaused by: "
kubelet.service: Main process exited, code=exited, status=255/EXCEPTION

**Our Kubelet Version - 1.16.11**

Error We are getting in below file at # L2376
https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/providers/v1/aws.go#L2376

**IMDS-V2** - https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/instancedata-data-retrieval.html

**Comment by cartermckinnon** [comment]
The AWS SDK added upport for IMDSv2 in 1.25.38: https://github.com/aws/aws-sdk-go/commit/1b7071ca4e1ebbffb85fc8187e501c3f830efe49

The 1.16 kubelet uses 1.16.26: https://github.com/kubernetes/kubernetes/blob/release-1.16/staging/src/k8s.io/legacy-cloud-providers/go.mod#L15

Unfortunately 1.16 has been out of support for a long time (not to mention the in-tree cloud providers have since been removed entirely). Your best bet is to update.

**Comment by ranjithvasireddy** [comment]
Thank you @cartermckinnon for the reply. So we need to update our Kubernetes clusters to 1.25.38 to support IMDSv2 . Basically we are using our own Bootstrapping scripts to Create AWS EC2 instances for Kubernetes.

**Comment by ranjithvasireddy** [comment]
Sure, Thanks @cartermckinnon We will try to Upgrade our Clusters to 1.18 to see if this issue will be fixed. Also, Anything we need to change from our end after the Upgrade like Sending a IMDS Token to Kubelet as extra Var?

**Comment by cartermckinnon** [comment]
The SDK will retrieve a token as needed, you don't need to pass anything extra.

**Comment by ranjithvasireddy** [comment]
Great Thanks @cartermckinnon . We will upgrade the clusters soon. I will keep it open for few days and will close the ticket.

**Comment by cartermckinnon** [comment]
Sure thing. To be clear though, this issue should be closed unless you encounter an issue with a version of Kubernetes that is still maintained -- 1.18 is no longer maintained and we don't track new issues on 1.18 releases.
