### ISSUE TITLE
Ignore route table entries that do not reference Nodes in a Kubernetes cluster

### ISSUE THREAD

**Issue by zuzzas** [kubernetes/cloud-provider-aws#627]
**What happened**:

```
E0309 13:31:09.337249       1 route_controller.go:119] Couldn't reconcile node routes: error listing routes: node with instanceID "i-00f82996a848bd437" not found
```

**What you expected to happen**:

Nothing bad.

**How to reproduce it (as minimally and precisely as possible)**:

I've got a route to a VPN instance that I've added manually to a route table that `cloud-provider-aws` manages.

**Anything else we need to know?**:

It happens [here](https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/providers/v1/aws_routes.go#L117).

/kind bug

**Comment by Marwan-Dalaty** [comment]
HI @k8s-ci-robot any update on the above?
