### ISSUE TITLE
ecr-credential-provider binaries as part of the release

### ISSUE THREAD

**Issue by dcarrion87** [kubernetes/cloud-provider-aws#633]
Would be handy to have binaries for the ecr-credential-provider as part of the release similar to:

https://github.com/Fred78290/aws-ecr-credential-provider/releases

amd64 Compatible binaries for 1.25, 1.26 and 1.27 in particular.

Would save from having to compile separately.

**Comment by james-callahan** [comment]
Duplicate of https://github.com/kubernetes/cloud-provider-aws/issues/512
