### ISSUE TITLE
Unable to deploy cluster onto AWS us-east-1 region

### ISSUE THREAD

**Issue by delpic** [kubernetes/cloud-provider-aws#64]
**What happened**:
I was in the process of running the `kubeadm init` command to initialize the first control plane for the cluster, but I ran into an issue when running this command as it times out. I had no issues deploying a k8s cluster with kubeadm prior to this, the only difference now is that I am using the aws cloud provider.

In syslog, I am seeing the following:
```
Nov 10 04:15:11 ip-XXXXXX kubelet[24132]: E1110 04:15:11.285928   24132 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.RuntimeClass: Get https://XXXXXX.elb.us-east-1.amazonaws.com:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
Nov 10 04:15:11 ip-XXXXXX kubelet[24132]: E1110 04:15:11.323234   24132 kubelet.go:2267] node "ip-XXXXX.ec2.internal" not found
Nov 10 04:15:11 ip-XXXXXX kubelet[24132]: E1110 04:15:11.423449   24132 kubelet.go:2267] node "ip-XXXXX.ec2.internal" not found
Nov 10 04:15:11 ip-XXXXXX kubelet[24132]: E1110 04:15:11.484386   24132 reflector.go:123] k8s.io/kubernetes/pkg/kubelet/kubelet.go:459: Failed to list *v1.Node: Get https://XXXXXXX.elb.us-east-1.amazonaws.com:6443/api/v1/nodes?fieldSelector=metadata.name%3Dip-XXXX.ec2.internal&limit=500&resourceVersion=0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
Nov 10 04:15:11 ip-XXXXXX kubelet[24132]: E1110 04:15:11.523611   24132 kubelet.go:2267] node "ip-XXXXX.ec2.internal" not found
Nov 10 04:15:11 ip-XXXXXX kubelet[24132]: E1110 04:15:11.623781   24132 kubelet.go:2267] node "ip-XXXXX.ec2.internal" not found
```
Reaching out for help on Slack, I got this response:
https://kubernetes.slack.com/archives/C2P1JHS2E/p1573444966468300

Looking into this further, the private DNS hostname does not match up with the format expected. This seems to only affect the us-east-1 region. Per:

https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-hostnames

I found this:
```
An Amazon-provided private (internal) DNS hostname resolves to the private IPv4 address of the instance, and takes the form ip-private-ipv4-address.ec2.internal for the us-east-1 Region, and ip-private-ipv4-address.region.compute.internal for other Regions (where private-ipv4-address is the reverse lookup IP address). You can use the private DNS hostname for communication between instances in the same network, but we can't resolve the DNS hostname outside the network that the instance is in.
```
With this, I went ahead to test a deployment in another region. I ran the same steps in the us-east-2 region and I had no issues there, using the aws cloud provider.

**What you expected to happen**:
Be able to deploy a Kubernetes cluster, using Kubeadm and the aws cloud provider, in the us-east-1 region.

**How to reproduce it (as minimally and precisely as possible)**:
`sudo kubeadm init --upload-certs --config=aws.yml`

aws.yml file:
```
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    cloud-provider: aws
clusterName: kube-test
controlPlaneEndpoint: XXXXXXXXXXXXX
controllerManager:
  extraArgs:
    cloud-provider: aws
    configure-cloud-routes: "false"
kubernetesVersion: stable
networking:
  podSubnet: 192.168.0.0/16
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: aws
```

**Anything else we need to know?**:
Haven't tried to deploy in other regions. But, I am guessing that this is only affecting us-east-1 per AWS' documentation.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.16.2`
- Cloud provider or hardware configuration: `AWS`
- OS (e.g. from /etc/os-release): `18.04.3 LTS (Bionic Beaver)`
- Kernel (e.g. `uname -a`): `Linux 4.15.0-1052-aws #54-Ubuntu SMP Tue Oct 1 15:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: NA
- Others: NA

/kind bug

**Comment by delpic** [comment]
This is no longer an issue. Closing.

**Comment by jhughes2112** [comment]
This is definitely an issue.  What happens in us-east-1* is that the availability zone is NOT part of the DNS, and the AWS Cloud Provider assumes it is.

```
Feb 01 09:16:56 ip-172-31-75-238.ec2.internal kubelet[115551]: I0201 09:16:56.870000  115551 aws.go:1251] Building AWS cloudprovider
Feb 01 09:16:56 ip-172-31-75-238.ec2.internal kubelet[115551]: I0201 09:16:56.870082  115551 aws.go:1211] Zone not specified in configuration file; querying AWS metadata service
```

Note the internal DNS is [ip].ec2.internal, not [ip].us-east-1f.ec2.internal, which differs from all the other zones around the world.
