### ISSUE TITLE
Could not deploy an AWS Network Load Balancer with multiple SSL certifications.

### ISSUE THREAD

**Issue by LYSingD** [kubernetes/cloud-provider-aws#645]
**What happened**:

I cannot deploy an AWS Network Load Balancer with multiple SSL certifications. The  service.beta.kubernetes.io/aws-load-balancer-ssl-cert annotation can only assign one SSL certificate from ACM

**What you expected to happen**:
I can deploy an AWS Network Load Balancer with multiple SSL certifications. The  service.beta.kubernetes.io/aws-load-balancer-ssl-cert annotation can assign multiple SSL certificate from ACM

**How to reproduce it (as minimally and precisely as possible)**:
In the annotations section, put multiple SSL ARN as string list in `service.beta.kubernetes.io/aws-load-balancer-ssl-cert`. Eg
```
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
service.beta.kubernetes.io/aws-load-balancer-type: nlb
service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/3e0ae8dd-d678-4cd0-97fd-d552ac264799, arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/8de13d30-1c2a-4cc8-8cae-53cb58449fb0"
service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxxxxx,subnet-xxxxxxxxx,subnet-xxxxxxxxx"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.24`
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):  Linux
- Kernel (e.g. `uname -a`): Linux
- Install tools:
- Others:

/kind bug

**Comment by kmala** [comment]
An NLB listener would accept only 1 certificate as far as i know. Can you explain your case a little bit more?

**Comment by ilyesAj** [comment]
@kmala sorry to bring this issue back, but i'm getting the same behavior . i think what @LYSingD is trying to do is to attach multiple certificates into the NLB. The listener wil get one default certificate but you can attach multiple optional certificates . You can see it in the AWS UI where you can find `default certificate ` section and `Listener certificates for SNI` section. 
https://aws.amazon.com/about-aws/whats-new/2019/09/elastic-load-balancing-network-load-balancers-now-supports-multiple-tls-certificates-using-server-name-indication/
can you please take a look ?

**Comment by LYSingD** [comment]
@ilyesAj , we eventually added those additional certificates via iac.
