### ISSUE TITLE
Allow `ecr-credential-provider` to generate credentials for any registry

### ISSUE THREAD

**Issue by jBouyoud** [kubernetes/cloud-provider-aws#668]
**What would you like to be added**: Allow `ecr-credential-provider` to generate credentials for any registry (only base restrictions on `CredentialProviderConfig`)

**Why is this needed**:
Today `ecr-credential-provider`, is limited to `public.ecr.aws` , and registry url compliant with [ecrPattern](https://github.com/kubernetes/cloud-provider-aws/blob/master/cmd/ecr-credential-provider/main.go#L45). 

In order to achieve this functionality we need to remove this restriction.

**End user use case** : 
Using an EKS Cluster, we need to mirror public registry where SLA aren't garrantee or with some IP Rate limits restrictions. 

In order to achieve that, I've setuped the followings : 
- ECR Pull through cache to `public.ecr.aws` , `quay.io` and `registry.k8s.io`
- Containerd configured to mirror `public.ecr.aws` , `quay.io` and `registry.k8s.io` to my private ECR registry
- Private registry is hosted on another account (cross account scenario), on the same aws region
- aws-ecr-credential-provider configured to generate credentials for : `public.ecr.aws` , `quay.io` and `registry.k8s.io` with a config file like : 
  ```json
  {
    "apiVersion": "kubelet.config.k8s.io/v1alpha1",
    "kind": "CredentialProviderConfig",
    "providers": [
      {
        "name": "ecr-credential-provider",
        "matchImages": [
          "*.dkr.ecr.*.amazonaws.com",
          "*.dkr.ecr.*.amazonaws.com/*",
          "*.dkr.ecr.*.amazonaws.com.cn",
          "*.dkr.ecr-fips.*.amazonaws.com",
          "*.dkr.ecr.*.c2s.ic.gov",
          "*.dkr.ecr.*.sc2s.sgov.gov",
          "quay.io",
          "public.ecr.aws",
          "registry.k8s.io"
        ],
        "defaultCacheDuration": "12h",
        "apiVersion": "credentialprovider.kubelet.k8s.io/v1alpha1"
      }
    ]
   }
  ```

* Current status : No credentials has been generated, and pull through cache aren't use 
* Expected status : Credentials should be generated (for the current node , on the same aws region, or an explicit configuration on `CredentialProviderConfig`) , to allow my node to use my private registry mirror for public registry.

**Potential solution**:

I wonder if it's really needed to _generate an error here_ and not relying on SDK region behavior (and potential user configuration in provider configuration - `AWS_REGION` env variable in `CredentialProviderConfig` for exemple).

By removing program error [here](https://github.com/kubernetes/cloud-provider-aws/pull/667/files#diff-61e97abee8e39e3bb484acf33a377325f9514a670e1a541c15a8a61eb9343f79R232) , with something like : 
```suggestion
if len(splitHost) != 6 {
  return "", nil
}
```
(further code updates will be probably needed ;-) ) 
this provider will rely on AWS SDK default behaviour, and let opportunity to users to handle more uses cases.
Relying on SDK default behavior will still throw an error when no region are configured (Eg. : `E0922 13:04:35.558288   57050 main.go:255] Error running credential provider plugin: MissingRegion: could not find region configuration` ) 

Ref.: https://github.com/kubernetes/cloud-provider-aws/pull/667#discussion_r1334174043

Sample working code modification : https://github.com/jBouyoud/cloud-provider-aws/commit/5a167d0ae233981db3a992dd767b1ff1f60fdcda

I'll be glad to help on this topic, please let me known how.
Regards

/kind feature

**Comment by cartermckinnon** [comment]
To make sure I understand, you want to be able to create a Pod using an image like `registry.k8s.io/foo:latest`. But you want `containerd` to *actually* pull and use `my-private-mirror.com/registry.k8s.io/foo:latest`?

I get why this could be handy, but I'd try to solve this as far up the stack (and as early in the Pod lifecycle) as possible. You could use a mutating admission webhook to rewrite the images of incoming Pod's to use your mirror, for example ( from a quick search, there's a handful of implementations of this out there). This would allow you to modify your mirror config more easily and would make the k8s API objects reflect the actual desired state.

**Comment by Preisschild** [comment]
Also, not all usecases can be handled with a mutating webhook, because some images are pulled without a podspec, such as the `registry.k8s.io/pause` image (my specific use case, also pull-through mirrored on AWS ECR)

**Comment by kmala** [comment]
> because some images are pulled without a podspec, such as the registry.k8s.io/pause image 

The only image i can think of being used without mention in pod spec is pause container and it can be updated using the containerd config https://kubernetes.io/docs/setup/production-environment/container-runtimes/#override-pause-image-containerd
If you want to update the control plane nodes images, then you must be creating your own control plane right? which would mean you should have access to use any image you want correct?

**Comment by Preisschild** [comment]
Overriding is possible, but then you'd have to additionally maintain the version in the tag.

The default pause / etcd images are set by my kubernetes distribution.

**Comment by cartermckinnon** [comment]
I don't think this is the best way to achieve the goal, but I'm not opposed to changing a couple lines in the `ecr-credential-provider` to unblock you.

It's worth considering that if you have any issues with your `containerd` mirror config, you could end up sending your ECR credentials to the wrong remote.
