### ISSUE TITLE
Invalid format for AWS instance 

### ISSUE THREAD

**Issue by doryer** [kubernetes/cloud-provider-aws#724]
**What happened**:

We've upgraded to k8s 1.25.15 and installed aws CCM in our cluster using kOps, since the upgrade we periodically see those error logs from aws CCM:

`E1102 13:36:37.503965 1 node_lifecycle_controller.go:185] error checking if node <instance-id> is shutdown: Invalid format for AWS instance ()
}`

We see that when node going up and joins the cluster, the node becomes ready and it not seems it effects the node scheduling but we still not sure why we see those Errors

**What you expected to happen**:

Not seeing erros on those nodes or more details error log

**How to reproduce it (as minimally and precisely as possible)**:

Running cloud controller manager with version v1.25.12 in k8s 1.25.15

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25.15
- Cloud provider or hardware configuration: AWS EC2, 
- OS (e.g. from /etc/os-release): Ubuntu 20.04.6
- Kernel (e.g. `uname -a`): 5.15.0-1037-aws
- Install tools: kOps
- Others:

/kind bug

**Comment by cartermckinnon** [comment]
What does the node's provider ID look like?

**Comment by cartermckinnon** [comment]
That's definitely the problem. Do you know what's setting the provider ID on your nodes?

**Comment by doryer** [comment]
> That's definitely the problem. Do you know what's setting the provider ID on your nodes?

I'm not sure, i will have a quick check. it is also contains the instance-id so it looks like aws:///eu-west-1a/<instance-id>
Anyway, what should it be to be valid ?

**Comment by doryer** [comment]
> That's definitely the problem. Do you know what's setting the provider ID on your nodes?

We're running the cluster with kOps so from docs seems like Node controller inside kops-controller is the one who applying this to the k8s node: https://kops.sigs.k8s.io/architecture/kops-controller/.
It is also contains the instance-id so it looks like aws:///eu-west-1a/
Anyway, what should it be to be valid?

**Comment by cartermckinnon** [comment]
>  It is also contains the instance-id so it looks like aws:///eu-west-1a/

Can you give me a complete example of what it looks like? The log message you included looks like the instance ID wasn't able to be parsed from the provider ID: https://github.com/kubernetes/cloud-provider-aws/blob/a1eb96d8ee3baffa8450e870c7360afa6ca836d2/pkg/providers/v1/instances.go#L82

I don't know how the provider ID is set in a kops cluster.

/kind support

**Comment by yogeek** [comment]
@cartermckinnon is it possible to /reopen this issue please ? We are seeing the same error messages in our clusters deployed with kubeadm and it seems related to the explanation above (race condition between the tool setting the providerID on the node - kops or kubelet - and the node controller)

**Comment by dims** [comment]
@yogeek do you mind opening a fresh issue with exact details from your clusters? (then cross link this issue from there)
