### ISSUE TITLE
duplicate functionality  with Load Balancer Controller

### ISSUE THREAD

**Issue by riuvshyn** [kubernetes/cloud-provider-aws#728]
Hello, I am abit confused by the fact that AWS cloud provider is having similar functionality as [Load Balancer Controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/)

If I have both aws cloud provider and aws lb controller running which component should be responsible for serving k8s Service annotations? 
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/
https://cloud-provider-aws.sigs.k8s.io/service_controller/
Both seems to have service controllers using same annotations...

/triage support

**Comment by oliviassss** [comment]
@riuvshyn, @taraszka, from AWS LBC v2.5.0 we add a webhook mutator to make the LBC the default controlle for service type of load balancer, to disable this feature you can set the helm chart value `enableServiceMutatorWebhook` to `false`. see more details from our release note: https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.5.0

**Comment by taraszka** [comment]
@oliviassss I know, I'd like to have the same for cloud-provider-aws, and let decide which to use using `LoadBalancerClass`

**Comment by riuvshyn** [comment]
@oliviassss same here, I want let LB controller to manage LBs not the CCM. 🙇🏽

**Comment by JoelSpeed** [comment]
Have you tried configuring the `--controllers` flag for the CCM? I believe `--controllers=*,-service` would disable the service controller, leaving all functionality then to the LB controller no?
