### ISSUE TITLE
Document use of custom endpoints 

### ISSUE THREAD

**Issue by flickerfly** [kubernetes/cloud-provider-aws#73]
**What would you like to be added**:
Documentation regarding the use of AWS Custom/VPC Endpoints for services like EC2.

**Why is this needed**:
I am deploying in an airgapped region of AWS and need to be able to access the custom endpoints as the traditional ones are unavailable to me. I can't seem to find documentation on how to accomplish this. 

/kind feature

**Comment by kapilt** [comment]
I was curious so went spelunking, from the golang sdk docs https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/ it looks like need explicit support in code, which the aws provider does have
https://github.com/kubernetes/legacy-cloud-providers/blob/master/aws/aws.go#L656

and its configured in the config file
https://github.com/kubernetes/legacy-cloud-providers/blob/master/aws/aws.go#L595

**Comment by flickerfly** [comment]
@kapilt Yep, it works, but finding out how to do it was a multi-day exploration for me so I'm recommending this get documented.
