### ISSUE TITLE
Provide 1.29 release

### ISSUE THREAD

**Issue by toabctl** [kubernetes/cloud-provider-aws#761]
kubernetes 1.29 is close so please provide a 1.29 release . This is required on our end to prepare Ubuntu AWS EKS images for the upcoming EKS 1.29 release . The images require the ecr-credential-provider plugin.

**Comment by kmala** [comment]
@toabctl there is new 1.29.0 tag and release branch created. are you unblocked now?

**Comment by cartermckinnon** [comment]
@toabctl the CredentialProviderRequest/CredentialProviderResponse API version is the only thing that matters for compatibility, so while it’s a good practice to ship the ecr-credential-provider with the same minor version as kubelet, it will very rarely be a blocking requirement for testing/dev.
