### ISSUE TITLE
Release Automation for Primary Artifacts

### ISSUE THREAD

**Issue by pi1814** [kubernetes/cloud-provider-aws#778]
Hi Team,

We observed that the project does not have the release automation for some of artifacts based on [comment](https://github.com/kubernetes/cloud-provider-aws/pull/773#discussion_r1428350347).

Is there any way in which we can help?

Tagging @puerco @Rohansjamadagni @eddie-knight

**Comment by mprenditore** [comment]
This would be great to have helm chart in sync with kubernetes releases.
