### ISSUE TITLE
EKS 1.15 - NLB TLS termination is failing when multiple ACM certificate ARN's are used

### ISSUE THREAD

**Issue by saiteja313** [kubernetes/cloud-provider-aws#80]
**What happened**:
EKS 1.15 - NLB TLS termination is not supporting multiple ACM certificateARN's

**What you expected to happen**:
When a service with NLB annotation is deployed, kube-controller-manager (AWS Cloud provider integration) should create/update Network Load Balancer listener with all the certificates listed as part of annotation "service.beta.kubernetes.io/aws-load-balancer-ssl-cert".

Service deployment fails with following error:
    
        Warning  SyncLoadBalancerFailed  6s service-controller  Error syncing load balancer: failed to ensure load balancer: Error creating load balancer listener: "CertificateNotFound: Certificate 'arn:aws:acm:us-east-1:xxxxxx:certificate/xxxxxxxx,arn:aws:acm:us-east-1:xxxxxxx:certificate/xxxxxxxxx' not found\n\tstatus code: 400, request id: 28c67c03-cf14-4dd3-bde7-28daab6dd524"

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a pod and expose it as service type LoadBalancer with following annotation. Make sure you pass two ACM ARN's as value.

    annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ACM_CERT_ARNS_HERE>  #use atleast two ARN's

Test pod manifest:
    
    apiVersion: apps/v1
    kind: Deployment
    metadata:
    creationTimestamp: null
    labels:
        run: nlb-tls-deploy
    name: nlb-tls-deploy
    spec:
    replicas: 1
    selector:
        matchLabels:
        run: nlb-tls-deploy
    strategy: {}
    template:
        metadata:
        creationTimestamp: null
        labels:
            run: nlb-tls-deploy
        spec:
        containers:
        - image: nginx
            name: nlb-tls-deploy
            resources: {}
    status: {}
    ---
    apiVersion: v1
    kind: Service
    metadata:
    creationTimestamp: null
    labels:
        run: nlb-tls-deploy
    name: nlb-tls-deploy
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ACM_CERT_ARN_HERE> #"arn:aws:acm:us-east-1:xxxxxxxx:certificate/xxxx,xxxxx "
    spec:
    ports:
    - port: 443
        protocol: TCP
        targetPort: 80
    selector:
        run: nlb-tls-deploy
    type: LoadBalancer
    status:
    loadBalancer: {}

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): EKS 1.15
- Cloud provider or hardware configuration: AWS

/kind bug

**Comment by dwightbiddle-ef** [comment]
We are running into this issue also  and are currently running an ELB per cert (not ideal!). Wondering if OP figured out an alternative way to do this or if anyone has any suggestions?

**Comment by andreamaruccia** [comment]
we have the same issue

**Comment by kireledan** [comment]
Based on the code for this section, it doesnt look like it splits this annotation to look for multiple certs. The action here would be to add support for multiple certs.  

https://github.com/kubernetes/legacy-cloud-providers/blob/337bfc5066299ed54615cd27f6b3dd70c1aaf0f9/aws/aws.go#L3734

**Comment by kireledan** [comment]
status is I've gotten this working for multiple certificates upon creation - update logic is being worked out

**Comment by fheinonen** [comment]
> status is I've gotten this working for multiple certificates upon creation - update logic is being worked out

@kireledan  Would you mind elaborating the partial solution you came up with?

**Comment by kireledan** [comment]
So far I've just modified the creation of the ELB to use the "AddListenerCertificate" method if multiple certs are seen in the annotation.  For updating, Im going to re-create the listener on each update if a certificate is removed (since you cant delete the default). Im not sure if this is the best route since something could happen between recreation and cause issues. However, Im not sure of the most efficient way of dealing with modifying certificates attached.

**Comment by nucleusv** [comment]
I add additional certificates for NLB via init-containers for nginx-ingress controller, it is very required to add additional certificates via annotations for NLB also.

**Comment by kireledan** [comment]
I've gotten a solution worked out. Writing up a PR now.

**Comment by M00nF1sh** [comment]
Hi @kireledan 
Is the UX like if multiple certs(comma-separate list) is specified, the first one will be used as default certs while others are additional cert?

We have implemented such certificate annotation UX for our NLB-IP Service controller(same set of annotations as this in-tree NLB Service support but with IP targeting).

**Comment by kireledan** [comment]
Noting here just for Github purposes even though we already talked --

Yes, the UX is similar to V2. First cert is the default, others are additional. It is a comma-separate list.

**Comment by jfreeland** [comment]
@kireledan do you intend to pick back up on https://github.com/kubernetes/kubernetes/pull/95208?

**Comment by kireledan** [comment]
I can't find any time to keep working on this. Anyone is totally free to pick this up. It's in working state, the logic just needs to be moved around according to the PR comments.

**Comment by SpootyMcSpoot** [comment]
Any update here?

**Comment by SpootyMcSpoot** [comment]
Any update here?

**Comment by probepark** [comment]
Any update?

**Comment by treksler** [comment]
> I add additional certificates for NLB via init-container for nginx-ingress controller, it is very required to add additional certificates via annotations for NLB also.

How do you add the additional NLB certs via an nginx-ingress controller init container? aws cli? curious to try this workaround. do you have an example?

also, can this issue be reopened?
it may become critical for me to be able to associate multiple acm certs with an NLB via nginx ingress annotations. 

also interested in other workarounds people are using. one cert with tons of subject alternate names?

**Comment by gtskaushik** [comment]
Please re-open this issue

**Comment by Spritekin** [comment]
Please reopen.

**Comment by gangstead** [comment]
I ended up fixing this by installing the AWS Load Balancer Controller on my EKS clusters (and specifying `service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip`).  The controller properly handles multiple ssl certs in the annotation.

**Comment by pham7quang** [comment]
@saiteja313 could you kindly reopen this issue? This issue still exists.

**Comment by olemarkus** [comment]
Are you using external CCM with EKS?

**Comment by pham7quang** [comment]
Thanks for the quick reply @olemarkus, I don't think I'm using an External CCM, is there a way I can confirm this?

**Comment by olemarkus** [comment]
Pretty sure you are not then. You should see the pod(s) running in `kube-system`.

**Comment by pham7quang** [comment]
The only pods in that namespace for me are: `aws-node`, `coredns`, `efs-csi-controller`, `efs-csi-node`, and `kube-proxy`. So I do not think I have any external CCM. Sorry for my ignorance but should I be using an External CCM to support multiple SSL Certs?

**Comment by olemarkus** [comment]
You should definitely be using it for claiming a bug exists in the external CCM repository :)

**Comment by zakirgl** [comment]
any updates?

**Comment by davem-git** [comment]
still a problem any update?

**Comment by gangstead** [comment]
The solution is to use AWSLoadBalancerController if you want multiple ACM certs.  It's annoying to have to install yet-another-controller but it works.  I'm surprised EKS doesn't have the AWS LB Controller available as an add-on like they do for the EBS CSI Driver which at this point is necessary for any EKS cluster.
