### ISSUE TITLE
TalosOSv1.5.5: AWS CCM can't find the instance via the API so it can't configure the nodes in peer region 

### ISSUE THREAD

**Issue by Rammurthy5** [kubernetes/cloud-provider-aws#836]
I have a TalosOS v1.5.5 with kubespan enabled and CCM installed cluster.

**What happened**:
CCM should configure all the worker nodes in the cluster but it is not if kubespan enabled and peer regional nodes are present.

**What you expected to happen**:
CCM should configure all the worker nodes if they are part of single cluster, and reachable.

**How to reproduce it (as minimally and precisely as possible)**:
Launch talosOS cluster following official [documentation](https://www.talos.dev/v1.6/talos-guides/install/cloud-platforms/aws/#configure-the-load-balancer), and add options to enable externalLoadBalancer. 
 
**Anything else we need to know?**:

E```
0122 13:23:49.763321    1 node_controller.go:236] error syncing 'ip-xxxx.region.compute.internal': failed to get provider ID for node ip-xxxx.region.compute.internal at cloudprovider: failed to get instance ID from cloud provider: instance not found, requeuing
I0122 13:23:49.780400    1 node_controller.go:427] Initializing node ip-xxxx.eu-west-1.compute.internal with cloud provider
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.29
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): talos 1.5.5
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

<!-- DO NOT EDIT BELOW THIS LINE -->
/kind bug

**Comment by cartermckinnon** [comment]
> peer regional nodes are present.

Do you mean the nodes and CCM are in different regions?

**Comment by Rammurthy5** [comment]
Control plane nodes on two different regions which are Vpc peered and kubespanned.

**Comment by cartermckinnon** [comment]
So, this particular failure is caused by CCM trying to call `ec2:DescribeImages` in the region it's running, for an instance in another region. I'd expect you to see more papercuts, because CCM assumes in many places that the AWS resources are in a single region. I don't think removing that assumption would be simple.

You could potentially run an instance of CCM in each region as a workaround.
