### ISSUE TITLE
Website does not have the correct trademark disclaimer

### ISSUE THREAD

**Issue by thisisobate** [kubernetes/cloud-provider-aws#837]
As part of our ongoing effort to https://github.com/cncf/techdocs/issues/198, we noticed that the website does not pass the trademark criteria on [CLOMonitor](https://clomonitor.io/search?foundation=cncf&not_passing_check=trademark_disclaimer&page=1).

To fix this:
Head to the source code of the website. In the `<footer>` section, add a **disclaimer** or **link** to the Linux foundation trademark disclaimer page:

**Disclaimer**
```
<footer>
   <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, 
         please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
   </p>
</footer>
```

**Link**
```
 <footer>
      <ul>
          <li><a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademarks</a></li>
      </ul>
 </footer>
```

**Comment by cartermckinnon** [comment]
We use `mkdocs` to generate that site, is there a recommended way to add this in our `mkdocs.yml` config?

Looks like we have a few options (`copyright`, `social` links, etc.): https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer

But there's also a "custom copyright" option that requires extending the standard mkdocs template. It'd be handy if that could be provided by the techdocs team 😄

**Comment by thisisobate** [comment]
@cartermckinnon unfortunately, the only way to fix this is by setting a "custom copyright" option. 
If you want the CNCF to assist you in creating one, I would advise you open a ticket on our [servicedesk platform](https://cncfservicedesk.atlassian.net/).
Hope that helps!

**Comment by cartermckinnon** [comment]
Makes sense, I'll see what I can do! 👍
