### ISSUE TITLE
GitHub repository does not link to the project website url

### ISSUE THREAD

**Issue by thisisobate** [kubernetes/cloud-provider-aws#838]
As part of our ongoing effort to [ensure all the websites within the CNCF meet the CLOMonitor guidelines](https://github.com/cncf/techdocs/issues/196), we noticed that cloud-provider-aws does not pass the website criteria on [CLOMonitor](https://clomonitor.io/search?not_passing_check=website&foundation=cncf&page=1). 

To fix this:
Edit [kubernetes/cloud-provider-aws](https://github.com/kubernetes/cloud-provider-aws) repository details. See Notary for example: 
<img width="1704" alt="Screenshot 2023-11-22 at 09 29 19" src="https://github.com/notaryproject/notary/assets/29557702/0b9dd1e3-f32b-42c6-adfc-a860ebad347b">

In the website section, add the link to the cloud-provider-aws website (https://cloud-provider-aws.sigs.k8s.io/). See Notary for example:
<img width="1704" alt="Screenshot 2023-11-22 at 09 30 15" src="https://github.com/notaryproject/notary/assets/29557702/c883c1c3-f9d7-4fcc-ae3c-fadf402d43cd">

Once done, feel free to close this issue as CLOMonitor will recrawl the page and update accordingly.

**Comment by cartermckinnon** [comment]
@dims can you paste this link into the repo metadata? I don't have the permissions.

**Comment by dims** [comment]
Done!

**Comment by cartermckinnon** [comment]
Thanks!

/close
