### ISSUE TITLE
AWS CCM DockerFile build for more than one platform 

### ISSUE THREAD

**Issue by mixeract** [kubernetes/cloud-provider-aws#839]
**What would you like to be added**:
The current Dockerfile for Cloud Provider AWS is primarily configured for the amd64 architecture. As the usage of different architectures (like ARM) is becoming more prevalent, especially in cloud-native environments, it would be beneficial for this project to support multi-platform Docker builds.

DockerFile reference https://github.com/kubernetes/cloud-provider-aws/blob/master/Dockerfile#L32

**Why is this needed**:
Supports users on different architectures, particularly important for ARM-based systems like AWS Graviton instance types. 

/kind feature

**Comment by cartermckinnon** [comment]
The Dockerfile is already set up to target whatever `--platform` you pass to buildx; I don't know why the platform of the golang image for the builder stage is hard-coded here. Removing it seems to work fine. @hakman did this have something to do with reproduceable builds?

**Comment by hakman** [comment]
@cartermckinnon I think so, probably can be removed now.
`ko` builds could also be used. Probably we should drop the Dockerfile in the future.

**Comment by cartermckinnon** [comment]
thanks! If you want to put up a PR to remove this line @mixeract, feel free 👍

**Comment by et304383** [comment]
@cartermckinnon @hakman opened #951

**Comment by olemarkus** [comment]
As mentioned in the PR, arm64 is already supported and published together with the amd64 images.

**Comment by et304383** [comment]
> As mentioned in the PR, arm64 is already supported and published together with the amd64 images.

My mistake. So is this issue already resolved?  Should it be closed?
