### ISSUE TITLE
cloud-provider-aws does not Prefer CLI Arguments for Configuring Kubernetes

### ISSUE THREAD

**Issue by aauren** [kubernetes/cloud-provider-aws#840]
**What happened**:

I attempted to pass `--master` and `--kubeconfig` to `cloud-provider-aws` and didn't see any change to the output of the provider. This resulted in `cloud-provider-aws` not being configured correctly in my cluster.

This resulted in the following error:

```
F0128 01:25:22.339300      26 main.go:84] unable to execute command: unable to load configmap based request-header-client-ca-file: Get "https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": dial tcp 10.96.0.1:443: i/o timeout
```

In the above, `10.96.0.1` is what the kube-apiserver would be reachable at, if my CNI was up and proxying requests to it's ClusterIP.

**What you expected to happen**:

I expected it to adhere to the CLI arguments that I passed.

**How to reproduce it (as minimally and precisely as possible)**:

* Run the [DaemonSet](https://github.com/kubernetes/cloud-provider-aws/blob/master/examples/existing-cluster/base/aws-cloud-controller-manager-daemonset.yaml) as documented
* Configure the arguments in the daemonset to attempt to use either `--kubeconfig` or `--master` and see that `aws-cloud-controller-manager` does not follow the defined configuration

**Anything else we need to know?**:

In my case, I found that this was caused by `aws-cloud-controller-manager` preferring the environment variables that Kubernetes sets:

* `KUBERNETES_SERVICE_HOST`
* `KUBERNETES_SERVICE_PORT`

instead of the CLI parameters passed.

This will be surprising for most users as other CLI tooling from Kubernetes like `kubectl` prefer the CLI arguments over environment variables.

It also makes it incredibly difficult to bootstrap a new cluster where the CNI is dependent on information from the cloud provider plugin in order to function correctly. As it will prefer the ClusterIP of the Kubernetes API server rather than the configuration that the user is attempting to override it with and result in a race condition.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.28.2
- Cloud provider or hardware configuration: AWS - `aws-cloud-controller-manager` `v1.29.1`
- OS (e.g. from /etc/os-release): `Ubuntu 22.04.3 LTS`
- Kernel (e.g. `uname -a`): `6.2.0-1018-aws`
- Install tools:
- Others:

/kind bug

**Comment by kmala** [comment]
aws cloud provider uses the upstream kubernetes cloud library and the error is coming from the [upstream code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go#L372). It is using a [different flag](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go#L283-L285) to override the kube config . Can you adding additional flag `authentication-kubeconfig` and verify if it works. We can create an issue upstream and see how they would like to proceed.

**Comment by aauren** [comment]
Adding `--authentication-kubeconfig` seemed to make the configuration work as well.

Can I ask why cloud-provider-aws has two separate flags for this? `--kubeconfig` is the normal flag so I wasn't expecting to find another flag for passing the kubeconfig again.
