### ISSUE TITLE
AWS NLB Deletion Protection

### ISSUE THREAD

**Issue by T00mm** [kubernetes/cloud-provider-aws#88]
**What would you like to be added:**

An annotation in the format of

service.beta.kubernetes.io/aws-load-balancer-deletion-protection: [true|false]

that will set the Deletion Protection of the ELB to True or False. (Default is False)

**Why is this needed:**

To protect the loadbalancer from accidental deletion by external sources.

/kind feature

**Comment by raelga** [comment]
In case anyone is interested, I had the same issue and ended developing a new operator to enable/disable the termination protection using annotations in the service object. Is in the early stages, but it works and is quite inoffensive.

https://github.com/3scale/aws-nlb-helper-operator

**Comment by NeckBeardPrince** [comment]
Can we reopen this?
/reopen
/remove-lifecycle rotten

**Comment by janarthanandev** [comment]
is there any update
