### ISSUE TITLE
Publish versioned Docker images

### ISSUE THREAD

**Issue by Eddman** [kubernetes/cloud-provider-aws#89]
**What would you like to be added**:
Currently I'm not able to find any official Docker image. We need a versioned Docker images published.

**Why is this needed**:
1) First of all the `aws-cloud-controller-manager` is supposed to run as Pod in a cluster. So Docker image is the ideal/expected format.
2) Right now there are some unofficial published images, but nobody wants to run any unofficial images within clusters with such privileges.
3) There is a number of supported versions of Kubernetes. The concrete image should support some concrete version, eg. For K8s 1.16 -> should use 1.16 K8s API.
4) `cloud-controller-manager` is also deprecated since 1.16. So there is no other replacement and this repository is the only official source now.

/kind feature

**Comment by chrisob** [comment]
:+1:, I was also unable to find an image for this in the past, and just gave up after looking :eyes:

**Comment by TBBle** [comment]
From https://github.com/kubernetes/cloud-provider-aws/issues/42#issuecomment-636351528
> Worth noting that we will likely cut an alpha version soon, we were just blocked on getting our GCR registry setup for a while (kubernetes/k8s.io#859).

**Comment by andrewsykim** [comment]
We have a published GCR registry now, see https://github.com/kubernetes/cloud-provider-aws/pull/107 

/close
