### ISSUE TITLE
Override automatic creation of security group rules for the NLB

### ISSUE THREAD

**Issue by jicowan** [kubernetes/cloud-provider-aws#90]
**What would you like to be added**:
Overrride the creation of an AWS security group rule, e.g. allow 0.0.0.0/0 inbound to the service node port, with a rule that allows you to specify a range of node ports or create an annotation that effectively disables the automatic creation of a security group rule. 
**Why is this needed**:
There are hard limits as to the number of SG rules you can create per ENI.  Customers who are using the NLB and creating lots of [NLB] services will hit this limit eventually.  By allowing customers to specify a range of ports, e.g. all node ports, they don't have to create a rule per service. 

/kind feature

**Comment by jicowan** [comment]
https://github.com/kubernetes/legacy-cloud-providers/blob/master/aws/aws.go#L3726-L3744

**Comment by jicowan** [comment]
https://github.com/kubernetes/legacy-cloud-providers/blob/6d365217b9361d728bd8622417919f94689635a0/aws/aws.go#L3726-L3744

**Comment by randomvariable** [comment]
@justinsb says: "Could potentially merge adjacent ports into a port range, but may have weird failure semantics (deleting a port in the middle of a range)"

**Comment by nckturner** [comment]
Do we want to solve this in the AWS cloud provider?

**Comment by randomvariable** [comment]
@jicowan could you describe your use case a bit more please?

/priority awaiting-more-evidence

**Comment by jicowan** [comment]
Ideally, I want the option to disable the automatic creation of SG rules or provide an array of existing rules to apply to the worker nodes. If I have lots of NLB services, I will eventually hit the limit for SG rules. To minimize the numbers of rules, forego creating a rule when it overlaps with an existing rule.

**Comment by throrin19** [comment]
Any news about this demand ? I have this problem now. I have to deploy more than 100 services with specific nlb for each of them. Actually I have 10 services and it cost 46 rules. The limit is 60 per security group and I can't find any information to avoid this creation and use default security group rules

**Comment by kishorj** [comment]
The ability to disable SG rules for NLB is available in aws-load-balancer-controller:v2.4.0, for more details -  https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.4.0
