### ISSUE TITLE
Allow to enable partial feature 

### ISSUE THREAD

**Issue by jaffcheng** [kubernetes/cloud-provider-aws#91]
**What would you like to be added**:
Config options to enable/disable handling of k8s resources
**Why is this needed**:
Adding these config options allows users to choose what k8s resources should be handled by AWS.

/kind feature

**Comment by andrewsykim** [comment]
> Config options to enable/disable handling of k8s resources

@jaffcheng can you expand on this a bit more please? Which k8s resources do you need enabled/disabled and why?

**Comment by andrewsykim** [comment]
fwiw, the kube-controller-manager and cloud-controller-manager has a `--controllers` flag where you can toggle certain controllers that operate against those resources.

**Comment by jaffcheng** [comment]
Hi @andrewsykim , thanks for the info. In our case we have a self-managed k8s cluster on AWS and we are trying to enable NLB based service but leave other resources disabled. I'll try `--controllers`.

**Comment by jaffcheng** [comment]
The above parameter works, Thanks!
